from pathlib import Path
src=Path('research/proof_frontier/2026-09-08/formal/full_ud/src/Theory/RSInterpolationKernel.lean').read_text()
s=src[:src.index("/-- info:")]
s=s.replace('import Theory.RSInterpolationMatrix','import Theory.CurveRSInterpolationMatrix')
s=s.replace('SpecializationKernels','CurveSpecializationKernels').replace('det_eq_zero_of_specializations','curve_det_eq_zero_of_specializations').replace('bounded_kernel_of_specializations','curve_bounded_kernel_of_specializations')
s=s.replace('(ωs f0 f1 : ι → F)', '(ωs : ι → F) (f : ι → F[X])')
s=s.replace('(fun i => f0 i + z * f1 i)', '(fun i => (f i).eval z)')
s=s.replace('(e deg : ℕ) (domain : ι ↪ F) (u : Fin 2 → ι → F) (S : Finset F)', '(cdeg e deg : ℕ) (domain : ι ↪ F) (f : ι → F[X]) (S : Finset F)\n    (hfdeg : ∀ i, (f i).natDegree ≤ cdeg)')
s=s.replace('(fun i => Polynomial.C (u 0 i) + Polynomial.X * Polynomial.C (u 1 i))', 'f')
s=s.replace('(fun i => u 0 i + z * u 1 i)', '(fun i => (f i).eval z)')
s=s.replace('CurveSpecializationKernels e deg domain (u 0) (u 1) S', 'CurveSpecializationKernels e deg domain f S')
s=s.replace('(hS : e+1 < S.card)', '(hS : cdeg*(e+1) < S.card)').replace('(hScard : e+1 < S.card)', '(hScard : cdeg*(e+1) < S.card)')
s=s.replace('natDegree ≤ e + 1', 'natDegree ≤ cdeg*(e + 1)').replace('natDegree ≤ e)', 'natDegree ≤ cdeg*e)').replace('natDegree ≤ e :=', 'natDegree ≤ cdeg*e :=')
s=s.replace('natDegree ≤ e+1', 'natDegree ≤ cdeg*(e+1)')
s=s.replace('have he1_lt : e + 1 < S.card := hS', 'have he1_lt : cdeg*(e+1) < S.card := hS')
s=s.replace('(BW_homMatrix_det_submatrix_natDegree_le_e_add_one (ι := ι) (F := F) e deg\n        (ωs := fun i => domain i) (f0 := fun i => u 0 i) (f1 := fun i => u 1 i)\n        (r := (r : Fin N → ι)))', '(BW_det_natDegree_le cdeg e deg domain f hfdeg\n        (r := (r : Fin N → ι)))')
s=s.replace('(BW_homMatrix_map_evalRingHom (ι := ι) (F := F) e deg (fun i => domain i)\n            (fun i => u 0 i) (fun i => u 1 i) z)', '(BW_map_eval e deg domain f z)')
s=s.replace('curve_det_eq_zero_of_specializations e deg domain u S hScard hgood r', 'curve_det_eq_zero_of_specializations cdeg e deg domain f S hfdeg hScard hgood r')
s=s.replace('BW_homMatrix_entry_natDegree_le_one (F := F) (ι := ι) e deg\n        (ωs := fun i => domain i) (f0 := fun i => u 0 i) (f1 := fun i => u 1 i)', 'BW_entry_natDegree_le cdeg e deg domain f hfdeg')
s=s.replace('BW_homMatrix_entry_natDegree_eq_zero_of_ge (F := F) (ι := ι) e deg\n        (ωs := fun i => domain i) (f0 := fun i => u 0 i) (f1 := fun i => u 1 i)', 'BW_entry_natDegree_zero e deg domain f')
s=s.replace('natDegree ≤ 1', 'natDegree ≤ cdeg').replace('_ ≤ 1 :=', '_ ≤ cdeg :=')
s=s.replace('(n := 1)', '(n := cdeg)')
s=s.replace('RS_exists_nonzero_kernelVec_of_det_submatrix_eq_zero_natDegree_le_one (ι := ι) (F := F) e K0', 'RS_exists_nonzero_kernelVec_of_det_submatrix_eq_zero_natDegree_le (ι := ι) (F := F) cdeg e K0')
s=s.replace('natDegree ≤ 1 + e', 'natDegree ≤ cdeg + cdeg*e').replace('Nat.add_le_add hA ha', 'Nat.add_le_add hA ha')
s=s.replace('≤ 1 + e := Nat.add_le_add hA ha', '≤ cdeg + cdeg*e := Nat.add_le_add hA ha')
s=s.replace('simpa [Nat.add_comm] using this', 'simpa [Nat.mul_add, Nat.add_comm] using this')
s=s.replace('(n := e + 1)', '(n := cdeg*(e + 1))')
s=s.replace('Direct polynomial-matrix interface;', 'Degree-M curve extension following BCIKS20 §6.1. Direct polynomial-matrix interface;')
s+='\nend Minidregg.RSInterpolation\n'
p=Path('/tmp/minidregg-polynomial-curve-full-ud-20260908/Theory/CurveRSInterpolationKernel.lean')
p.write_text(s)
