// @generated by metatheory/EmitLayoutManifest.lean — DO NOT EDIT BY HAND.
//
// The rotated EffectVM column layout, exported from the Lean that DEFINES it and that emits the
// constraint descriptors READING it. The Rust producer (`turn::rotation_witness`) WRITES these
// same columns, and the audit gates check them — so all three now read one source instead of
// three hand-maintained mirrors.
//
// This module exists because the mirrors drifted, and drift here is not a lint failure — it is a
// soundness bug. The perms/VK completion weld once read limb 37 (`revoked_root` lane-0) while the
// producer wrote limb 38, and every honest setPermissions/setVerificationKey turn was UNSAT.
//
// Regenerate with the ack-gated emit pipeline (`scripts/emit_descriptors.py`); never hand-edit.

/// the v1 EffectVM face width — the base every rotated member graduates from
pub const EFFECT_VM_WIDTH: usize = 188;

/// pre-iroot limbs in one rotated block — projected from the verified RotatedLayout
pub const NUM_PRE_LIMBS: usize = 187;

/// one rotated state block's span (BEFORE and AFTER each occupy B_SPAN columns)
pub const B_SPAN: usize = 251;

/// column offset from a member's face to its AFTER block (= B_SPAN)
pub const AFTER_BLOCK_OFF: usize = 251;

/// the caveat region's span
pub const C_SPAN: usize = 45;

/// the 29-limb MANIFEST fold's carrier, in-region — an INTERMEDIATE of the chain, not the published commitment
pub const C_MANIFEST_COMMIT: usize = 38;

/// the DFA route-commitment (rc) carrier, in-region — ABSORBED into the published caveat commitment (the rc FOLD), which is what forces these columns
pub const C_RC_OFF: usize = 39;

/// the rc extension's first carrier: hash [manifest commit, rc0, rc1, rc2]
pub const C_RC_CARRIER: usize = 43;

/// the PUBLISHED caveat commitment carrier, in-region — caveatCommitRc over the manifest AND the rc carrier; the column rotPins binds to PI piBase+3
pub const C_COMMIT: usize = 44;

/// in-appendix base of the FIELDS-CANONICITY region (= 2*B_SPAN + C_SPAN, past both blocks and the caveat region). Its 7 aux columns per (block, slot) are what makes Canonical9's NoWrap leg expressible; the producer MUST fill them or every honest turn is UNSAT.
pub const CANON9_REGION_OFF: usize = 547;

/// aux columns one (block, slot) canonicity gadget uses, in order: r, q0, q1, v0, v0b, v1, v1b
pub const CANON9_PER_SLOT: usize = 7;

/// the fields-canonicity region's span (2 blocks * 8 slots * 7 aux columns)
pub const CANON9_SPAN: usize = 112;

/// 2*B_SPAN + C_SPAN + CANON9_SPAN — the rotated appendix appended to the v1 face
pub const APPENDIX_SPAN: usize = 659;

/// poseidon2-chip SITES the rotated appendix contributes (2 blocks + the caveat region incl. the rc fold). Graduation appends 7 lane columns per site, so this is the multiplier the Rust host width uses — it was a hand-carried arithmetic literal in trace_rotated.rs and it drifted.
pub const ROT_APPENDIX_SITES: usize = 138;

/// committed record/authority digest limb
pub const B_RECORD_DIGEST: usize = 24;

/// committed capability-root limb
pub const B_CAP_ROOT: usize = 25;

/// committed nullifier-root limb
pub const B_NULLIFIER_ROOT_OFF: usize = 26;

/// committed commitments-root limb
pub const B_COMMITMENTS_ROOT: usize = 27;

/// committed heap-root limb
pub const B_HEAP_ROOT: usize = 28;

/// committed lifecycle limb
pub const B_LIFECYCLE: usize = 29;

/// committed epoch limb
pub const B_EPOCH: usize = 30;

/// last SCALAR pre-iroot limb (disc/perms/vk/mode/fields-root ride past it)
pub const B_COMMITTED_HEIGHT: usize = 31;

/// WAVE-1 committed discriminant limb
pub const B_DISC: usize = 32;

/// WAVE-2 committed permissions-digest limb (lane 0 of the faithful 8-felt group)
pub const B_PERMS: usize = 33;

/// WAVE-2 committed verification-key-digest limb (lane 0 of the 8-felt group)
pub const B_VK: usize = 34;

/// WAVE-3 committed mode limb
pub const B_MODE: usize = 35;

/// WAVE-3 committed fields-root digest limb
pub const B_FIELDS_ROOT: usize = 36;

/// REVOKED-ROOT flag-day limb — inserted at 37, shifting every limb >= 37 by +1
pub const B_REVOKED_ROOT: usize = 37;

/// FIRST perms-digest completion limb; permsHash[1..7] ride B_PERMS_COMPLETION..+6. The producer writes these lanes and the in-circuit weld reads them: ONE source.
pub const B_PERMS_COMPLETION: usize = 38;

/// FIRST vk-digest completion limb; vkHash[1..7] ride B_VK_COMPLETION..+6
pub const B_VK_COMPLETION: usize = 45;

/// the iroot limb (pre-iroot limbs end here)
pub const B_IROOT: usize = 187;

/// the state-commitment limb
pub const B_STATE_COMMIT: usize = 188;

/// in-block base of the chained-absorption carriers — READ OFF `rotV3SitesAt`'s first emitted site, so the producer writes the columns the descriptors bind. Rust carried this by hand and it rotted across the 178 -> 184 flag day (180 vs 186): the producer overwrote four pre-limbs plus iroot/state_commit and every rotated member was UNSAT.
pub const B_CHAIN_BASE: usize = 189;

/// chain carriers per block: they fill `[B_CHAIN_BASE, B_SPAN)` exactly
pub const B_NUM_CHAIN: usize = 62;

/// in-block offset of the first S2-deleted column (the 1-felt state_commit digest)
pub const S2_CARRIER_OFF: usize = 188;

/// one S2-deleted carrier band's width (state_commit digest + B_NUM_CHAIN chain carriers)
pub const S2_CARRIER_SPAN: usize = 63;

/// the S2-deleted graduated chip-lane band's width (7 lanes per deleted block site)
pub const S2_LANE_SPAN: usize = 882;

/// state register index of the first committed field (fields[0]); the AFTER-block field octet holds register r(FIELD_BASE+i) at octet index i, so octet_index(r) = r - FIELD_BASE
pub const FIELD_BASE: usize = 3;

/// in-block column base of the AFTER-block committed fields[0..8] lane-0 octet (the app-root weld octet): weldsAt maps base+CUSTOM_APP_FIELD_ROT_BASE+i ↔ stateBase+FIELD_BASE+i
pub const CUSTOM_APP_FIELD_ROT_BASE: usize = 4;

/// width of the app-root field octet (8 field lane-0 limbs)
pub const CUSTOM_APP_FIELD_OCTET_LEN: usize = 8;

/// in-block base of the child_vk carrier octet (app-PI octet base 0 of [89, 97, 105])
pub const B_CHILD_VK_OCTET: usize = 89;

/// in-block base of the contract_hash carrier octet (app-PI octet base 1 of [89, 97, 105])
pub const B_CONTRACT_HASH_OCTET: usize = 97;

/// in-block base of the public_key carrier octet (app-PI octet base 2 of [89, 97, 105])
pub const B_PUBKEY_OCTET: usize = 105;

/// ninth lane of the child_vk carrier NONET (KeyLanes9.keyToLanes9 lane 8)
pub const B_CHILD_VK_NINTH_LANE: usize = 184;

/// ninth lane of the contract_hash carrier NONET (KeyLanes9.keyToLanes9 lane 8)
pub const B_CONTRACT_HASH_NINTH_LANE: usize = 185;

/// ninth lane of the OWNER-KEY carrier NONET. The eight-lane octet at B_PUBKEY_OCTET cannot injectively hold 32 bytes; this column is what makes the committed nonet determine exactly one key (Emit.KeyCanonicity9Emit.keyCanon9_determines_the_owner_key_deployed).
pub const B_PUBKEY_NINTH_LANE: usize = 186;

/// range width of nonet lanes 0..7 (2^29 < p, so no lane reduces)
pub const KEY_LANE_BITS: usize = 29;

/// range width of nonet lane 8. NARROWER by construction: 2^256 / (2^29)^8 = 2^24. A uniform 29-bit check on lane 8 admits [0,...,0,2^24], which decodes byte-for-byte to the all-zero key — see keyCanon9_rejects_the_forged_nonet.
pub const KEY_TOP_BITS: usize = 24;

/// One faithful-8 group: lane 0 followed by seven completion columns.
pub type Felt8Group = [usize; 8];

/// Every named group, emitted verbatim from `rotated187.groupTable`.
pub const ROTATED_GROUP_TABLE: [Felt8Group; 10] = [
    [24, 12, 13, 14, 15, 16, 17, 18],
    [25, 52, 53, 54, 55, 56, 57, 58],
    [26, 68, 69, 70, 71, 72, 73, 74],
    [27, 75, 76, 77, 78, 79, 80, 81],
    [28, 59, 60, 61, 62, 63, 64, 65],
    [33, 38, 39, 40, 41, 42, 43, 44],
    [34, 45, 46, 47, 48, 49, 50, 51],
    [36, 66, 67, 19, 20, 21, 22, 23],
    [37, 82, 83, 84, 85, 86, 87, 88],
    [0, 169, 170, 171, 172, 173, 174, 175],
];

pub const AUTHORITY_DIGEST_GROUP: Felt8Group = ROTATED_GROUP_TABLE[0];
pub const CAP_ROOT_GROUP: Felt8Group = ROTATED_GROUP_TABLE[1];
pub const NULLIFIER_ROOT_GROUP: Felt8Group = ROTATED_GROUP_TABLE[2];
pub const COMMITMENTS_ROOT_GROUP: Felt8Group = ROTATED_GROUP_TABLE[3];
pub const HEAP_ROOT_GROUP: Felt8Group = ROTATED_GROUP_TABLE[4];
pub const PERMS_GROUP: Felt8Group = ROTATED_GROUP_TABLE[5];
pub const VK_GROUP: Felt8Group = ROTATED_GROUP_TABLE[6];
pub const FIELDS_ROOT_GROUP: Felt8Group = ROTATED_GROUP_TABLE[7];
pub const REVOKED_ROOT_GROUP: Felt8Group = ROTATED_GROUP_TABLE[8];
pub const CELLS_ROOT_GROUP: Felt8Group = ROTATED_GROUP_TABLE[9];

/// Compatibility/readability alias used by the Rust disjointness tooth.
pub const ALL_FELT8_GROUPS: [Felt8Group; 10] = ROTATED_GROUP_TABLE;

/// The scalar limbs that carry no faithful-8 completion group.
pub const ROTATED_SINGLES: [usize; 16] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 29, 30, 31, 32, 35];

/// The carrier-material octet BASES (each occupies `base .. base + 8`).
pub const ROTATED_OCTET_BASES: [usize; 3] = [89, 97, 105];

/// The NINTH lane of each carrier octet, positionally parallel to `ROTATED_OCTET_BASES`. NOT adjacent to its octet: never reconstruct with a stride. Each is an ABSORBED pre-limb, so `wireCommitR` folds it into `state_commit` — which is the whole point.
pub const ROTATED_OCTET_NINTH_LANES: [usize; 3] = [184, 185, 186];

/// Every `fields[0..8]` completion lane column, in layout order (lanes 1..8 of each of the 8 slots — deliberately NON-CONTIGUOUS: the ninth lane of slot `j` is `176 + j`).
pub const ROTATED_FIELDS_LANE_COLS: [usize; 64] = [
    113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
    132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150,
    151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 176,
    177, 178, 179, 180, 181, 182, 183,
];

/// The legacy cells-completion slot (empty since `cells` became a named group).
pub const ROTATED_CELLS_COMPLETION: [usize; 0] = [];

/// Unoccupied pad columns. EMPTY at the nine-lane geometry — the two former pads (176, 177) were consumed by the fields nonet.
pub const ROTATED_PADS: [usize; 0] = [];

/// `ROTATED_FIELD_LANE_COL[slot][lane]` — the column carrying lane `lane` of `fields[slot]`.
/// Lane 0 is the welded v1-face limb, lanes 1..7 the historical completion window, lane 8 the
/// flag-day ninth lane. NON-CONTIGUOUS BY DESIGN: never reconstruct this with a stride.
pub const ROTATED_FIELD_LANE_COL: [[usize; 9]; 8] = [
    [4, 113, 114, 115, 116, 117, 118, 119, 176],
    [5, 120, 121, 122, 123, 124, 125, 126, 177],
    [6, 127, 128, 129, 130, 131, 132, 133, 178],
    [7, 134, 135, 136, 137, 138, 139, 140, 179],
    [8, 141, 142, 143, 144, 145, 146, 147, 180],
    [9, 148, 149, 150, 151, 152, 153, 154, 181],
    [10, 155, 156, 157, 158, 159, 160, 161, 182],
    [11, 162, 163, 164, 165, 166, 167, 168, 183],
];

/// Completion lanes per committed field slot (lanes 1..=8 — the VALUE8/nonet weld width).
pub const ROTATED_FIELD_COMPLETION_LANES: usize = 8;

/// `KEY_COMMIT_QUAD_IDX[q][j]` — quad `q`'s `j`-th input LANE of the committed owner-key
/// NONET, emitted from the AIR's own `CarrierOctetGates.quadIdx`. The four published KEY_COMMIT
/// teeth are `chip_absorb_all_lanes(4, [nonet[KEY_COMMIT_QUAD_IDX[q][j]]; 4])[0]`.
///
/// ⚑ EVERY lane 0..=8 appears (`quadIdx_covers_every_lane`), and lane 8 appears ONLY at `[2][0]`
/// (`quadIdx_row2_reads_the_ninth_lane`). Lane 8 carries source bit 255 = an Ed25519 key's
/// x-sign, so a matrix that omits it publishes identical teeth for a key and its negation — which
/// is exactly what the deployed member did until 2026-08-08. NEVER hand-edit this table.
pub const KEY_COMMIT_QUAD_IDX: [[usize; 4]; 4] =
    [[0, 1, 2, 3], [4, 5, 6, 7], [8, 0, 4, 2], [1, 5, 3, 7]];

/// The nonet lane count the KEY_COMMIT quads index into.
pub const KEY_NONET_LANES: usize = 9;

/// Derive the app-root field OCTET INDEX from a state register slot: the AFTER-block
/// `fields[0..8]` octet holds field register `r(FIELD_BASE + i)` at octet index `i`, so
/// `octet_index_of_register(r) == r - FIELD_BASE` — the single Lean-authored query the fold's
/// app-root weld reads (killing the hand `reg("winner") - 3`).
pub const fn octet_index_of_register(reg: usize) -> usize {
    reg - FIELD_BASE
}
