"""Construct the parameter-only Lean instance from the public native constructor capture.
No relation or witness equations are produced here: DirectedRnsScaler owns them.
"""
import json,re,math
from pathlib import Path
HERE=Path(__file__).resolve().parent
CAP=HERE.parents[1]/'learn_infer_only/experiments/end_to_end/nonlinear_successor_2026_09_08/public_trace/native_scaler_constants.json'
a=json.loads(CAP.read_text());d=a['native_RnsScaler_constructor_debug']
def arr(name):
 s=d[d.index('    '+name+': ')+len('    '+name+': '):];end=s.index('],')+1
 # nested arrays need balanced brackets
 depth=0
 for j,c in enumerate(s):
  depth+=(c=='[')-(c==']')
  if depth==0: return json.loads(s[:j+1].replace(',\n        ]','\n        ]').replace(',\n    ]','\n    ]'))
def crt(v,qs):
 Q=math.prod(qs);return sum(x*(Q//q)*pow(Q//q,-1,q) for x,q in zip(v,qs))%Q
qs=a['base'];ps=a['extended_base'];Q=math.prod(qs);P=math.prod(ps);t=a['t']
assert int(a['factor_denominator'])==Q and int(a['factor_numerator'])==t
gamma=crt(arr('gamma'),qs);nativeomega=arr('omega');omega=[crt([r[i] for r in nativeomega],qs) for i in range(len(ps))]
thetaG=[lo+(hi<<64) for lo,hi in zip(arr('theta_garner_lo'),arr('theta_garner_hi'))]
thetaF=[(-1 if sign else 1)*(lo+(hi<<64)) for lo,hi,sign in zip(arr('theta_omega_lo'),arr('theta_omega_hi'),arr('theta_omega_sign'))]
assert re.search(r'theta_garner_shift: 125,',d)
assert all(re.search(rf'{name}: 0,',d) for name in ['theta_gamma_lo','theta_gamma_hi'])
# Independent public integer reconstruction of the native projections and directed theta.
garners=[(P//q)*pow(P//q,-1,q) for q in ps]
assert gamma==(t*P//Q)%Q and t*P%Q==0
for i,G in enumerate(garners):
 O=(t*G+Q//2)//Q
 assert omega[i]==O%Q
 assert thetaG[i]==((G<<125)+P//2)//P
 assert thetaF[i]==-(-( (1<<127)*(t*G-Q*O))//Q)
def vec(xs):return '!['+','.join(map(str,xs))+']'
s='''/- Public native-constructor constants; generated by generate_instance.py.
Only constants are imported. Generic signed source forms and compiler own all equations. -/
import Compiler.DirectedRnsScaler
namespace Minidregg.Compiler.NonlinearRnsInstance
open Minidregg.Compiler.DirectedRnsScaler Minidregg.Compiler.SignedMatrix
open Minidregg.Compiler.NativeKernelPlan
set_option autoImplicit false
set_option maxRecDepth 20000
set_option maxHeartbeats 3000000
'''
s+=f'def params : Params 9 4 where\n  sourceBase := {vec(ps)}\n  targetBase := {vec(qs)}\n  Q := {Q}\n  thetaG := {vec(thetaG)}\n  thetaF := {vec(thetaF)}\n  omega := {vec(omega)}\n  gamma := {gamma}\n  dG := 2^125\n  dF := 2^127\n  wOffset := 2^70\n  uOffset := 2^70\n'
s+='''
def profile : Layout := ⟨39,23,23,9,45,20⟩
def rows (i : Fin profile.rows) : Row profile.groups := (forms params).get ⟨i.val,by change i.val<23; exact i.isLt⟩

theorem paramsValid : Valid params := by
  constructor
  · decide
  · decide
  · decide
  · intro i; fin_cases i <;> decide
  · intro i; fin_cases i <;> decide
  · intro i; fin_cases i <;> decide

def source := SignedMatrix.system profile rows

end Minidregg.Compiler.NonlinearRnsInstance
'''
s+="\n/-- info: 'Minidregg.Compiler.NonlinearRnsInstance.paramsValid' depends on axioms: [propext, Classical.choice, Quot.sound] -/\n#guard_msgs in\n#print axioms Minidregg.Compiler.NonlinearRnsInstance.paramsValid\n"
(HERE/'Compiler/NonlinearRnsInstance.lean').write_text(s)
(HERE/'results/parameter_projection.json').write_text(json.dumps({'source_count':len(ps),'target_count':len(qs),'Q':str(Q),'canonical_gamma':str(gamma),'canonical_omega':list(map(str,omega)),'thetaG':list(map(str,thetaG)),'thetaF':list(map(str,thetaF)),'native_projection_and_directed_constants_equal':True,'theta_gamma_zero':True,'garner_shift':125,'profile':[39,23,23,9,45,20]},indent=2)+'\n')
print('generated constant-only instance; native public projections and directed constants match')
