//! Poseidon2 hash function over BabyBear with proven parameters from Plonky3.
//!
//! Parameters sourced from `p3-baby-bear` (Plonky3 repository) with 128-bit
//! security proofs from the Poseidon2 paper (https://eprint.iacr.org/2023/323).
//!
//! Configuration:
//! - Field: BabyBear (p = 2^31 - 2^27 + 1)
//! - Width: 16 field elements
//! - S-box: x^7
//! - External (full) rounds: 8 (4 initial + 4 final)
//! - Internal (partial) rounds: 13
//! - External linear layer: MDSMat4 circulant [2,3,1,1] applied blockwise
//! - Internal linear layer: 1 + Diag(V) where V is optimized for BabyBear
//!
//! Round constants generated by the Grain LFSR with parameters:
//!   field_type=1, alpha=7 (exp_flag=0), n=31, t=16, R_F=8, R_P=13

use crate::field::BabyBear;

/// Poseidon2 state width (number of field elements in state).
pub const WIDTH: usize = 16;

/// Number of external (full) rounds.
pub const EXTERNAL_ROUNDS: usize = 8;

/// Number of internal (partial) rounds.
pub const INTERNAL_ROUNDS: usize = 13;

/// Total rounds.
pub const TOTAL_ROUNDS: usize = EXTERNAL_ROUNDS + INTERNAL_ROUNDS;

/// S-box exponent for BabyBear (x^7).
const SBOX_ALPHA: u32 = 7;

/// Initial external round constants (4 rounds x 16 elements).
/// From BABYBEAR_POSEIDON2_RC_16_EXTERNAL_INITIAL in p3-baby-bear.
const RC_EXT_INIT: [[u32; 16]; 4] = [
    [
        0x69cbb6af, 0x46ad93f9, 0x60a00f4e, 0x6b1297cd, 0x23189afe, 0x732e7bef, 0x72c246de,
        0x2c941900, 0x0557eede, 0x1580496f, 0x3a3ea77b, 0x54f3f271, 0x0f49b029, 0x47872fe1,
        0x221e2e36, 0x1ab7202e,
    ],
    [
        0x487779a6, 0x3851c9d8, 0x38dc17c0, 0x209f8849, 0x268dcee8, 0x350c48da, 0x5b9ad32e,
        0x0523272b, 0x3f89055b, 0x01e894b2, 0x13ddedde, 0x1b2ef334, 0x7507d8b4, 0x6ceeb94e,
        0x52eb6ba2, 0x50642905,
    ],
    [
        0x05453f3f, 0x06349efc, 0x6922787c, 0x04bfff9c, 0x768c714a, 0x3e9ff21a, 0x15737c9c,
        0x2229c807, 0x0d47f88c, 0x097e0ecc, 0x27eadba0, 0x2d7d29e4, 0x3502aaa0, 0x0f475fd7,
        0x29fbda49, 0x018afffd,
    ],
    [
        0x0315b618, 0x6d4497d1, 0x1b171d9e, 0x52861abd, 0x2e5d0501, 0x3ec8646c, 0x6e5f250a,
        0x148ae8e6, 0x17f5fa4a, 0x3e66d284, 0x0051aa3b, 0x483f7913, 0x2cfe5f15, 0x023427ca,
        0x2cc78315, 0x1e36ea47,
    ],
];

/// Final external round constants (4 rounds x 16 elements).
const RC_EXT_FINAL: [[u32; 16]; 4] = [
    [
        0x7290a80d, 0x6f7e5329, 0x598ec8a8, 0x76a859a0, 0x6559e868, 0x657b83af, 0x13271d3f,
        0x1f876063, 0x0aeeae37, 0x706e9ca6, 0x46400cee, 0x72a05c26, 0x2c589c9e, 0x20bd37a7,
        0x6a2d3d10, 0x20523767,
    ],
    [
        0x5b8fe9c4, 0x2aa501d6, 0x1e01ac3e, 0x1448bc54, 0x5ce5ad1c, 0x4918a14d, 0x2c46a83f,
        0x4fcf6876, 0x61d8d5c8, 0x6ddf4ff9, 0x11fda4d3, 0x02933a8f, 0x170eaf81, 0x5a9c314f,
        0x49a12590, 0x35ec52a1,
    ],
    [
        0x58eb1611, 0x5e481e65, 0x367125c9, 0x0eba33ba, 0x1fc28ded, 0x066399ad, 0x0cbec0ea,
        0x75fd1af0, 0x50f5bf4e, 0x643d5f41, 0x6f4fe718, 0x5b3cbbde, 0x1e3afb3e, 0x296fb027,
        0x45e1547b, 0x4a8db2ab,
    ],
    [
        0x59986d19, 0x30bcdfa3, 0x1db63932, 0x1d7c2824, 0x53b33681, 0x0673b747, 0x038a98a3,
        0x2c5bce60, 0x351979cd, 0x5008fb73, 0x547bca78, 0x711af481, 0x3f93bf64, 0x644d987b,
        0x3c8bcd87, 0x608758b8,
    ],
];

/// Internal round constants (13 scalars). From BABYBEAR_POSEIDON2_RC_16_INTERNAL.
const RC_INTERNAL: [u32; 13] = [
    0x5a8053c0, 0x693be639, 0x3858867d, 0x19334f6b, 0x128f0fd8, 0x4e2b1ccb, 0x61210ce0, 0x3c318939,
    0x0b5b2f22, 0x2edb11d5, 0x213effdf, 0x0cac4606, 0x241af16d,
];

/// Internal diagonal d_i = 1 + V[i].
/// V = [-2, 1, 2, 1/2, 3, 4, -1/2, -3, -4, 1/2^8, 1/4, 1/8, 1/2^27, -1/2^8, -1/16, -1/2^27]
pub static INTERNAL_DIAG: [BabyBear; WIDTH] = [
    BabyBear(2013265920),
    BabyBear(2),
    BabyBear(3),
    BabyBear(1006632962),
    BabyBear(4),
    BabyBear(5),
    BabyBear(1006632961),
    BabyBear(2013265919),
    BabyBear(2013265918),
    BabyBear(2005401602),
    BabyBear(1509949442),
    BabyBear(1761607682),
    BabyBear(2013265907),
    BabyBear(7864321),
    BabyBear(125829121),
    BabyBear(16),
];

/// Cached round constants from Plonky3 Grain LFSR derivation.
pub static ROUND_CONSTANTS: std::sync::LazyLock<Vec<[BabyBear; WIDTH]>> =
    std::sync::LazyLock::new(compute_round_constants);

// crypto index loops kept verbatim
#[allow(clippy::needless_range_loop)]
fn compute_round_constants() -> Vec<[BabyBear; WIDTH]> {
    let mut constants = Vec::with_capacity(TOTAL_ROUNDS);
    for round in 0..EXTERNAL_ROUNDS / 2 {
        let mut rc = [BabyBear::ZERO; WIDTH];
        for j in 0..WIDTH {
            rc[j] = BabyBear::new(RC_EXT_INIT[round][j]);
        }
        constants.push(rc);
    }
    for round in 0..INTERNAL_ROUNDS {
        let mut rc = [BabyBear::ZERO; WIDTH];
        rc[0] = BabyBear::new(RC_INTERNAL[round]);
        constants.push(rc);
    }
    for round in 0..EXTERNAL_ROUNDS / 2 {
        let mut rc = [BabyBear::ZERO; WIDTH];
        for j in 0..WIDTH {
            rc[j] = BabyBear::new(RC_EXT_FINAL[round][j]);
        }
        constants.push(rc);
    }
    constants
}

/// The Poseidon2 permutation state.
#[derive(Clone, Debug)]
pub struct Poseidon2State {
    pub state: [BabyBear; WIDTH],
}

impl Poseidon2State {
    /// Create a new state initialized to zero.
    pub fn new() -> Self {
        Self {
            state: [BabyBear::ZERO; WIDTH],
        }
    }

    /// Create a state from field elements (remaining positions zero-padded).
    pub fn from_elements(elements: &[BabyBear]) -> Self {
        let mut state = [BabyBear::ZERO; WIDTH];
        for (i, &e) in elements.iter().take(WIDTH).enumerate() {
            state[i] = e;
        }
        Self { state }
    }

    /// Apply the S-box: x -> x^7.
    #[inline]
    pub fn sbox(x: BabyBear) -> BabyBear {
        x.pow(SBOX_ALPHA)
    }

    /// Apply the external linear layer: MDSMat4 [2,3,1,1] applied blockwise + wider.
    // crypto index loops kept verbatim
    #[allow(clippy::needless_range_loop)]
    pub fn external_linear_layer(&mut self) {
        // Apply 4x4 MDS to each chunk of 4
        for cs in (0..WIDTH).step_by(4) {
            let (x0, x1, x2, x3) = (
                self.state[cs],
                self.state[cs + 1],
                self.state[cs + 2],
                self.state[cs + 3],
            );
            let t01 = x0 + x1;
            let t23 = x2 + x3;
            let t0123 = t01 + t23;
            let t01123 = t0123 + x1;
            let t01233 = t0123 + x3;
            self.state[cs] = t01123 + t01; // 2x0+3x1+x2+x3
            self.state[cs + 1] = t01123 + x2 + x2; // x0+2x1+3x2+x3
            self.state[cs + 2] = t01233 + t23; // x0+x1+2x2+3x3
            self.state[cs + 3] = t01233 + x0 + x0; // 3x0+x1+x2+2x3
        }
        // Wider: add column sums
        let mut sums = [BabyBear::ZERO; 4];
        for k in 0..4 {
            for j in (0..WIDTH).step_by(4) {
                sums[k] += self.state[j + k];
            }
        }
        for i in 0..WIDTH {
            self.state[i] += sums[i % 4];
        }
    }

    /// Apply the internal linear layer: (1 + Diag(V)) * x.
    /// x_i' = sum(x) + (d_i - 1) * x_i
    // crypto index loops kept verbatim
    #[allow(clippy::needless_range_loop)]
    pub fn internal_linear_layer(&mut self) {
        let diag = &INTERNAL_DIAG;
        let sum: BabyBear = self
            .state
            .iter()
            .copied()
            .fold(BabyBear::ZERO, |a, b| a + b);
        for i in 0..WIDTH {
            self.state[i] = sum + (diag[i] - BabyBear::ONE) * self.state[i];
        }
    }

    /// Apply the full Poseidon2 permutation.
    // crypto index loops kept verbatim
    #[allow(clippy::needless_range_loop)]
    pub fn permute(&mut self) {
        let rc = &*ROUND_CONSTANTS;

        // Initial linear layer (per Poseidon2 spec)
        self.external_linear_layer();

        // First half of external rounds
        for round in 0..EXTERNAL_ROUNDS / 2 {
            // Add round constants
            for i in 0..WIDTH {
                self.state[i] += rc[round][i];
            }
            // Full S-box layer
            for i in 0..WIDTH {
                self.state[i] = Self::sbox(self.state[i]);
            }
            // External linear layer
            self.external_linear_layer();
        }

        // Internal rounds
        for round in 0..INTERNAL_ROUNDS {
            let rc_idx = EXTERNAL_ROUNDS / 2 + round;
            // Add round constant to first element only
            self.state[0] += rc[rc_idx][0];
            // Partial S-box (only first element)
            self.state[0] = Self::sbox(self.state[0]);
            // Internal linear layer
            self.internal_linear_layer();
        }

        // Second half of external rounds
        for round in 0..EXTERNAL_ROUNDS / 2 {
            let rc_idx = EXTERNAL_ROUNDS / 2 + INTERNAL_ROUNDS + round;
            // Add round constants
            for i in 0..WIDTH {
                self.state[i] += rc[rc_idx][i];
            }
            // Full S-box layer
            for i in 0..WIDTH {
                self.state[i] = Self::sbox(self.state[i]);
            }
            // External linear layer
            self.external_linear_layer();
        }
    }
}

/// Apply the external linear layer to a state array (standalone version).
pub fn apply_external_linear_layer(state: &[BabyBear; WIDTH]) -> [BabyBear; WIDTH] {
    let mut ps = Poseidon2State { state: *state };
    ps.external_linear_layer();
    ps.state
}

/// Apply the internal linear layer to a state array (standalone version).
pub fn apply_internal_linear_layer(state: &[BabyBear; WIDTH]) -> [BabyBear; WIDTH] {
    let diag = &INTERNAL_DIAG;
    let sum: BabyBear = state.iter().copied().fold(BabyBear::ZERO, |a, b| a + b);
    let mut result = [BabyBear::ZERO; WIDTH];
    for i in 0..WIDTH {
        result[i] = sum + (diag[i] - BabyBear::ONE) * state[i];
    }
    result
}

/// Compute one full (external) round of Poseidon2.
pub fn compute_full_round(
    state: &[BabyBear; WIDTH],
    round_constants: &[BabyBear; WIDTH],
) -> [BabyBear; WIDTH] {
    let mut s = [BabyBear::ZERO; WIDTH];
    for i in 0..WIDTH {
        s[i] = Poseidon2State::sbox(state[i] + round_constants[i]);
    }
    apply_external_linear_layer(&s)
}

/// Compute one partial (internal) round of Poseidon2.
pub fn compute_partial_round(
    state: &[BabyBear; WIDTH],
    round_constant: BabyBear,
) -> [BabyBear; WIDTH] {
    let mut s = *state;
    s[0] = Poseidon2State::sbox(s[0] + round_constant);
    apply_internal_linear_layer(&s)
}

/// Compute the expected next state for a given round index (0-indexed).
pub fn compute_round(state: &[BabyBear; WIDTH], round_idx: usize) -> [BabyBear; WIDTH] {
    let rc = &*ROUND_CONSTANTS;
    if round_idx < EXTERNAL_ROUNDS / 2 {
        compute_full_round(state, &rc[round_idx])
    } else if round_idx < EXTERNAL_ROUNDS / 2 + INTERNAL_ROUNDS {
        compute_partial_round(state, rc[round_idx][0])
    } else if round_idx < TOTAL_ROUNDS {
        compute_full_round(state, &rc[round_idx])
    } else {
        *state
    }
}

/// Hash 4 field elements using Poseidon2 (4-to-1 compression).
/// This is used for the 4-ary Merkle tree internal nodes.
///
/// Input: 4 child hashes (each a single field element)
/// Output: 1 parent hash (a single field element)
///
/// # Domain Separation Scheme
///
/// This module uses a consistent domain separation scheme across all hash functions
/// to prevent cross-domain collisions. The Poseidon2 state is partitioned as:
///
/// - **Rate region** (positions 0..3): absorbs input data
/// - **Capacity region** (positions 4..15): domain separation tags and padding
///
/// Domain tags by function:
/// - `hash_4_to_1`: position 4 = arity (4), positions 5..15 = 0
/// - `hash_2_to_1`: position 4 = arity (2), positions 5..15 = 0
/// - `hash_many`:   position 4 = input length, positions 5..15 = 0
/// - `hash_fact`:   positions 0..4 = data, position 5 = 0xFACF marker, position 6 = 1 (leaf flag)
///
/// These tags are non-overlapping: `hash_4_to_1` and `hash_2_to_1` use arity in pos 4,
/// `hash_many` uses length in pos 4 (which can only equal 2 or 4 if the input IS length 2/4,
/// but the rate absorption pattern differs), and `hash_fact` uses positions 5-6 which are
/// always zero in the other functions.
pub fn hash_4_to_1(inputs: &[BabyBear; 4]) -> BabyBear {
    let mut state = Poseidon2State::new();
    // Rate portion: inputs[0..4]
    state.state[0] = inputs[0];
    state.state[1] = inputs[1];
    state.state[2] = inputs[2];
    state.state[3] = inputs[3];
    // Capacity portion: domain separation tag
    state.state[4] = BabyBear::new(4); // arity tag
    // state[5..15] remain zero (capacity)

    state.permute();
    state.state[0]
}

/// Hash 2 field elements using Poseidon2 (2-to-1 compression).
pub fn hash_2_to_1(left: BabyBear, right: BabyBear) -> BabyBear {
    let mut state = Poseidon2State::new();
    state.state[0] = left;
    state.state[1] = right;
    state.state[4] = BabyBear::new(2); // arity tag

    state.permute();
    state.state[0]
}

/// Hash an arbitrary number of field elements (sponge construction).
/// Rate = 4, capacity = 12.
pub fn hash_many(inputs: &[BabyBear]) -> BabyBear {
    let rate = 4;
    let mut state = Poseidon2State::new();
    // Domain separation: encode length in capacity
    state.state[4] = BabyBear::new(inputs.len() as u32);

    // Absorb phase
    for chunk in inputs.chunks(rate) {
        for (i, &elem) in chunk.iter().enumerate() {
            state.state[i] += elem;
        }
        state.permute();
    }

    // Squeeze: return first element
    state.state[0]
}

/// Hash inputs into a faithful **8-felt** (~248-bit, ~124-bit-collision) digest via the Poseidon2
/// sponge — the wide-output primitive for the light-client-faithful state commitment.
///
/// Identical absorb to [`hash_many`] (same rate-4 absorb, same length-in-capacity domain separation),
/// so `hash_many(xs) == hash_many_8(xs)[0]` is NOT guaranteed and MUST NOT be relied on — this is a
/// distinct, wider digest. The squeeze follows the textbook sponge discipline: read the rate-4 block,
/// permute, read the rate-4 block again → 8 genuinely distinct permutation outputs that each depend on
/// the entire input. (Conservative vs reading `state[0..8]` from one final state, which would expose 4
/// capacity felts; the squeeze-permute-squeeze keeps every output a rate-position squeeze.)
///
/// This primitive is live in the exact fields/nullifier trees, where every
/// intermediate Merkle node is itself an eight-felt sponge digest.  It must
/// not be bolted only onto the final squeeze of a one-felt chain: that would
/// merely launder a 31-bit intermediate collision.  See
/// `.docs-history-noclaude/FAITHFUL-STATE-COMMITMENT.md`.
pub fn hash_many_8(inputs: &[BabyBear]) -> [BabyBear; 8] {
    let rate = 4;
    let mut state = Poseidon2State::new();
    // Domain separation: encode length in capacity (matches `hash_many`).
    state.state[4] = BabyBear::new(inputs.len() as u32);

    // Absorb phase (identical to `hash_many`).
    for chunk in inputs.chunks(rate) {
        for (i, &elem) in chunk.iter().enumerate() {
            state.state[i] += elem;
        }
        state.permute();
    }

    // Squeeze 8: rate-4 block, permute, rate-4 block again.
    let mut out = [BabyBear::ZERO; 8];
    out[0] = state.state[0];
    out[1] = state.state[1];
    out[2] = state.state[2];
    out[3] = state.state[3];
    state.permute();
    out[4] = state.state[0];
    out[5] = state.state[1];
    out[6] = state.state[2];
    out[7] = state.state[3];
    out
}

/// **THE faithful 8-felt chaining compression — ONE Poseidon2 permutation over an arity-≤11
/// seed, exposing 8 output lanes** (Phase B-ROTATION).
///
/// This is the SINGLE-PERMUTATION primitive the faithful per-cell state commitment chains on:
/// each chain step is `d8' = single_perm_compress(d0..d7 ‖ limb0,limb1,limb2)[0..8]` — the
/// 8-felt carrier `d8` plus up to 3 fresh limbs absorbed in ONE permutation (arity ≤ 11 =
/// `descriptor_ir2::CHIP_RATE`), the next 8-felt carrier read off lanes `state[0..8]`. Every
/// intermediate carrier is 8 felts — there is NO 31-bit intermediate (the anti-laundering
/// crux: a 1-felt-chain-with-wide-final-squeeze is the FORBIDDEN laundered version).
///
/// The seed convention is byte-identical to the in-circuit poseidon2 chip's wide arity-11 row
/// (`descriptor_ir2::chip_absorb_lanes` / `perm_lanes`): the inputs seed lanes `state[0..n]`
/// (n = `inputs.len()`, n ≤ 11), the capacity lanes `state[n..16]` are zero, ONE permutation
/// runs, and lanes `state[0..8]` of the permuted state ARE the 8-felt output. We read the final
/// state off [`poseidon2_trace`] — the SAME function the chip witness generator
/// (`poseidon2_permute_aux_witness`) uses — so a cell/turn computation of this primitive is
/// byte-identical to the trace's chip lane carriers.
///
/// `inputs.len()` MUST be ≤ 11 (the chip's `CHIP_RATE`); the chain's three site arities are
/// 4 (the head, no carrier yet), 11 (a carrier ‖ 3 limbs), and 9 (the final carrier ‖ iroot).
pub fn single_perm_compress(inputs: &[BabyBear]) -> [BabyBear; 8] {
    debug_assert!(
        inputs.len() <= 11,
        "single_perm_compress: arity {} exceeds chip rate 11",
        inputs.len()
    );
    let mut st = [BabyBear::ZERO; WIDTH];
    for (i, &x) in inputs.iter().enumerate() {
        st[i] = x;
    }
    let trace = poseidon2_trace(&st);
    let final_state = trace[trace.len() - 1];
    core::array::from_fn(|i| final_state[i])
}

/// **THE faithful 8-felt rotated state commitment — the wide twin of the 1-felt chain**
/// (Phase B-ROTATION).
///
/// Folds the pre-iroot limb list and the iroot into a genuine 8-felt digest (~248-bit,
/// ~124-bit collision, matching the proof's ~130-bit FRI soundness — closing the #1
/// light-client soundness floor where the 1-felt commitment is ~31-bit, collision in seconds).
///
/// The chain SHAPE mirrors the 1-felt `wire_commit` exactly so the absorption order and the
/// limb→site assignment are unchanged: a 4-wide head over the first four limbs, 3-wide groups
/// while ≥ 3 pre-iroot limbs remain, the iroot absorbed ALONE last. The DIFFERENCE: the
/// running accumulator `d` is 8 felts (not 1), and each step is a single arity-≤11
/// [`single_perm_compress`] over `d8 ‖ fresh`, NOT a rate-4 `hash_many` returning 1 felt:
///
/// * head: `d8 = single_perm_compress([l0, l1, l2, l3])` (arity 4)
/// * group: `d8 = single_perm_compress(d8 ‖ [lc, lc+1, lc+2])` (arity 11)
/// * leftover (if any): `d8 = single_perm_compress(d8 ‖ [lc])` (arity 9)
/// * final: `d8 = single_perm_compress(d8 ‖ [iroot])` (arity 9) → the 8-felt commitment
///
/// EVERY intermediate `d8` is 8 felts; the final `d8` IS the commitment. The Lean twin is
/// `EffectVmEmitRotationR.wireCommitR8` over an 8-felt `chainFrom8` carrier.
pub fn wire_commit_8(pre_limbs: &[BabyBear], iroot: BabyBear) -> [BabyBear; 8] {
    let mut d = single_perm_compress(&[pre_limbs[0], pre_limbs[1], pre_limbs[2], pre_limbs[3]]);
    let mut col = 4;
    let n = pre_limbs.len();
    while col < n {
        let remaining = n - col;
        let mut seed = Vec::with_capacity(11);
        seed.extend_from_slice(&d);
        if remaining >= 3 {
            seed.push(pre_limbs[col]);
            seed.push(pre_limbs[col + 1]);
            seed.push(pre_limbs[col + 2]);
            col += 3;
        } else {
            seed.push(pre_limbs[col]);
            col += 1;
        }
        d = single_perm_compress(&seed);
    }
    let mut seed = Vec::with_capacity(9);
    seed.extend_from_slice(&d);
    seed.push(iroot);
    single_perm_compress(&seed)
}

/// **THE CHIP-FAITHFUL 8-felt rotated state commitment — the byte-twin of `fill_wide_block`** (the
/// wide-carrier producer the circuit PUBLISHES). Identical chain SHAPE to [`wire_commit_8`] (4-wide
/// head, arity-11 body groups, arity-11-padded iroot final) but each step is the chip table's
/// [`chip_absorb_all_lanes`] — i.e. the SAME arity-tagged seeding the in-circuit `TID_P2` chip
/// lookups derive (`st[4] = arity` for narrow arities; the `seed456` blend for arity 7/11; the wide
/// lane tail). The two chains DIVERGE: [`wire_commit_8`]'s plain [`single_perm_compress`] seeds the
/// raw inputs with NO arity tag, so its head (arity 4) leaves `st[4] = 0` where the chip seeds
/// `st[4] = 4` — the chains differ from the head on. The CIRCUIT's published wide carrier IS this
/// chip chain (`chip_absorb_all_lanes` per `fill_wide_block` step), so the deployed executor MUST
/// anchor the 8 wide PIs against THIS primitive — the flip's cell-side cutover repoints
/// `compute_canonical_state_commitment_v9_felt8` here.
pub fn wire_commit_8_chip(pre_limbs: &[BabyBear], iroot: BabyBear) -> [BabyBear; 8] {
    use crate::descriptor_ir2::chip_absorb_all_lanes;
    let n = pre_limbs.len();
    let mut d = chip_absorb_all_lanes(4, &[pre_limbs[0], pre_limbs[1], pre_limbs[2], pre_limbs[3]]);
    let mut col = 4usize;
    while col < n {
        let remaining = n - col;
        let mut seed = [BabyBear::ZERO; 11];
        seed[..8].copy_from_slice(&d);
        let arity = if remaining >= 3 {
            seed[8] = pre_limbs[col];
            seed[9] = pre_limbs[col + 1];
            seed[10] = pre_limbs[col + 2];
            col += 3;
            11
        } else {
            seed[8] = pre_limbs[col];
            col += 1;
            9
        };
        d = chip_absorb_all_lanes(arity, &seed);
    }
    // final: the iroot rides the wide arity-11 absorb (`d8 ‖ iroot ‖ 0 ‖ 0`) — the chip AIR pins
    // `in7..in10 == 0` for every non-11 arity, so the final is the arity-11 row with two trailing
    // zero limb lanes (binding-preserving: `single_perm_compress` is invariant to them).
    let mut seed = [BabyBear::ZERO; 11];
    seed[..8].copy_from_slice(&d);
    seed[8] = iroot;
    chip_absorb_all_lanes(11, &seed)
}

/// Hash arbitrary bytes into a single BabyBear field element via Poseidon2.
///
/// The preimage is [`BabyBear::bytes_to_lanes`] — a four-lane base-`2^16` BYTE-COUNT header then
/// the bytes in little-endian `u16` pairs — so **distinct inputs have distinct preimages**
/// (Lean `Dregg2.Circuit.BytesLanes.bytesToLanes_injective`, from a total decoder and a
/// machine-checked left inverse).
///
/// # ⚑ What changed on 2026-08-01, and what did NOT
///
/// This used to be `hash_many(BabyBear::from_bytes_packed(data))`, and that composition was
/// collidable in two independent ways at **cost 0** — the NUL-append (`hash_bytes(b"foo") ==
/// hash_bytes(b"foo\0")`, because the packer zero-filled the final partial 4-byte chunk while the
/// sponge tag counted FELTS) and the mod-`p` chunk alias at equal length (53.1% of `u32` chunks
/// had a `+p` sibling). Both are gone: no preimage collision exists at all.
///
/// ⚠ **AND THE OUTPUT IS STILL ONE FELT, WHICH IS A DIFFERENT DEFECT AND IS NOT CLOSED.**
/// `log2(p) = 30.906891`, so an unstructured collision search on this digest costs the birthday
/// bound
///
/// ```text
///     2^(30.906891 / 2)  =  2^15.4534   ≈  44,900 evaluations
/// ```
///
/// — milliseconds. `docs/DESIGN-canonical-byte-felt-codec.md` §2.3 bans that shape by name
/// (`Digest1`: *"There is no security boundary where that is acceptable"*). Neither fix reaches
/// the other: no widening of the squeeze removes an append-collision in the preimage, and no
/// repair of the preimage removes a birthday collision in a 31-bit codomain. Use [`hash_bytes_8`]
/// wherever the sink can hold eight felts (`2^123.63`).
///
/// # ⚑ THE CALLER SWEEP, 2026-08-01 — who is still allowed to call this, and why
///
/// Every production caller was classified. **Do not add one without landing in a class below.**
/// 306 grep hits over 59 files reduce to ~10 production files; the rest are HOMONYMS — three
/// crates define a LOCAL `fn hash_bytes` over blake3 (`dungeon-on-dregg/src/campaign.rs`,
/// `dreggnet-offerings/src/operation.rs`, `fhegg-fhe/src/distributed_bfv_correlation.rs`) and
/// several more have local VARIABLES named `*_hash_bytes`.
///
/// **MIGRATED to [`hash_bytes_8`] (the felt was the only binding):**
/// * `zkoracle-prove`'s `content_commitment` / `template_commitment` — reached a committed,
///   chain-linked `TurnReceipt` slot via `dungeon_on_dregg::narrator::attestation_commit_field`.
///   Exhibit: `dungeon-on-dregg/tests/attestation_commit_wide_old_admits_new_rejects.rs`
///   (41,522 evaluations / 3.27 s to a byte-identical narration event).
/// * `cell::program::eval::hash_preimage32` — the Poseidon2 hash-LOCK behind `PreimageGate` /
///   `KeyRotationGate`, where a forged preimage was not merely accepted but INSTALLED as the
///   cell's key set. Exhibit: `cell/tests/preimage_gate_wide_old_admits_new_rejects.rs`
///   (67,066 evaluations / 0.82 s). Schema epoch 22 → 23.
///
/// **LEFT, because a BYTE-EXACT companion is committed alongside** (each call site names where
/// its companion lives, because the argument is not reconstructible from the line):
/// `storage::bucket_commitment::fold_leaves` and `starbridge-apps/site-host`'s `content_root`,
/// whose `coll = hash_bytes(key)` is a heap collection id while the key itself is bound
/// injectively inside the 8-felt object/asset digest that rides into `wire_commit_8`'s `pre`;
/// and — since 2026-08-03 — `sandstorm_bridge::cell::var_coll`, whose companion is
/// `var_leaf_digest8` (a `hash_bytes_8` image over `DOMAIN ‖ len(key) ‖ key ‖ value`, spread
/// across the entry's eight lane leaves), so `var_coll` decides only WHERE a leaf sits.
///
/// ⚠ **(B) means "no FORGERY", not "no cost".** All three of those sites address a sorted heap by
/// the narrow felt, and `heap_root::assert_addr_unique` **panics** on two leaves sharing an
/// address — fail-closed, but a panic. `sandstorm_bridge` already priced that residual as
/// availability. `storage::bucket_commitment::verify_opening` had it reachable from an UNTRUSTED
/// `Deserialize`-derived `ObjectOpening`, i.e. an unauthenticated remote abort at the same
/// `2^15.4534`; it now refuses an ambiguous leaf list at leg (0) instead
/// (`storage/tests/bucket_opening_coll_collision_dos.rs`). When classifying a site (B), say what
/// the collision DOES buy, not merely what it does not.
///
/// **LEFT, not security-bearing:** the two `hash_bytes(DOMAIN)` tags in those same two folds —
/// compile-time constants with no free parameter, so no search exists at any price and the
/// birthday figure does not apply.
///
/// **NAMED, NOT MIGRATED — the sink is one felt in a place Rust does not own.** Each says so at
/// its own definition, with the cost and the owner: `exec_lean::nullifier::addr_of` (the
/// `MapAbsent` IMT key; **Lean emit work**, and ⚑ it needs the base-2^29 NONET — a KEY needs
/// injectivity over 256 bits and eight lanes carry 247.26, so **`2^123.63` is a hash-NODE figure
/// and does not transfer**), and the two sel4 `crypto-floor` portal returns
/// (`dreggcf_blake3_to_field`, `dreggcf_keyed_mac`), whose width is the `uint64_t` C ABI in
/// `sel4/dregg-pd/executor-pd/scripts/crypto-floor.c` and the Lean portal declaration.
///
/// # ⚑ RE-CENSUSED 2026-08-06 — the sweep is COMPLETE, and three of its entries were STALE
///
/// An independent grep-zero re-census resolved every non-comment `hash_bytes` token in the tree
/// to a definition (two definitions are this one and its byte-verbatim out-of-workspace twin at
/// `sel4/…/crypto-floor/src/poseidon2.rs:261`; there are no re-exports and no aliased imports).
/// It found **the same eleven production call sites and no others**, so the caller list above is
/// exhaustive. Three entries needed correcting.
///
/// **1. `sandstorm_bridge::cell::{var_addr, var_value_felt}` no longer exist** — the `/var` repair
/// landed 2026-08-03 and those two functions are gone; the module now spreads a `hash_bytes_8`
/// leaf digest over eight lane leaves. Moved to the (B) list above.
///
/// **2. ⚠ THE STATED BLOCKER ON BOTH `wasm` SITES WAS FALSE.** They were left with *"`wasm` does
/// not compile at HEAD — a sibling lane owns it"*. Measured 2026-08-06:
/// `cargo check --manifest-path wasm/Cargo.toml --target wasm32-unknown-unknown` finishes in
/// **2m00s, four warnings, zero errors** (`wasm` is excluded from the workspace by
/// `Cargo.toml`'s own comment, so `cargo check --workspace` never reaches it — which is why a
/// green tree looked consistent with the claim).
///
/// **3. …and with that premise gone, neither `wasm` site is (A). Both are (C) AT HEAD, and
/// saying otherwise manufactures a wound.** Re-derived from the consuming code:
///
/// * `generate_predicate_proof`'s `fact_hash` → `FactBinding::predicate_sym` → column
///   `PREDICATE_SYM = 5`. **Nothing anywhere maps an attribute key to that felt.**
///   `verify_predicate_proof(proof_json, threshold, fact_commitment)` takes `fact_commitment` as a
///   caller-supplied `u32`, and the descriptor's leg 2 blinds it with a secret per-showing
///   `blinding`, so no verifier can recompute `hash_bytes(key)` even in principle; the extension
///   ships the attribute key beside the proof as a **plaintext string**
///   (`extension/src/background.ts:2061`). An attacker who wants a proof to read as being about a
///   different attribute renames that string — cost 0, no collision required. Widening this felt
///   would close nothing. ⚠ **Say the real defect instead of the flattering one: the fact
///   IDENTITY is unbound at the verifier, at any felt width.** Flip condition: the first verifier
///   that recomputes `predicate_sym` from a claimed key makes this (A), and the sink is then the
///   deployed column — Lean emit work plus a VK rotation.
/// * `prove_anonymous_membership`'s `agent_id_hash` / `set_root`: **there is no verifier in the
///   tree at all.** The function emits no proof — `proof_size` is a hand-computed estimate and
///   the body says "in a real system this would be a STARK" (already recorded at
///   `audits/AUDIT-wasm.md:151`) — and its consumer stores `set_root` into a report field
///   (`extension/src/background.ts:6165`) that nothing checks. No gate exists that a collision
///   could make accept. Flip condition: when the ring proof becomes a real STARK with a verifier
///   that re-folds the member set, the identity felt IS the binding — and note the sink then is
///   this crate's own `#[derive(Serialize)] struct MembershipResult { blinded_leaf: u32, … }`,
///   declared fifty lines below the call, i.e. a HOST reshape and not an AIR one. It must not be
///   deferred as if it were Lean's.
///
/// **Net: no (A) site remains that Rust alone can close.** Every survivor is (B), (C), or behind
/// a Lean emit / a C ABI — which is exactly why a blanket migration of this function's callers
/// would be wrong, and why this function survives rather than being deleted in favour of
/// [`hash_bytes_8`].
///
/// ⓘ **The squeeze has NO in-AIR counterpart** — measured across `metatheory/` and
/// `circuit/descriptors/` twice, on 2026-08-01. `BytesLanes.lean` stops at the PREIMAGE and
/// defines no sponge; every Lean hash carrier is felt-/`Nat`-domain; the "in-AIR `hash_bytes`
/// recompute" named at `effect_vm/authority_digest_weld.rs:57` is an arity-2 felt-domain chip
/// lookup in a gadget with zero production callers. Changing this function's SQUEEZE rotates no
/// VK and re-emits no descriptor. Changing its PREIMAGE (`bytes_to_lanes`) is a different
/// question and does reshape one descriptor — see `circuit-prove/src/zkoracle_leaf_adapter.rs`.
pub fn hash_bytes(data: &[u8]) -> BabyBear {
    hash_many(&BabyBear::bytes_to_lanes(data))
}

/// **The eight-felt companion of [`hash_bytes`]** — same injective preimage, same rate-4 absorb,
/// the squeeze-permute-squeeze of [`hash_many_8`].
///
/// This is the one to reach for at a security boundary: `~2^123.63` birthday over `p^8` against
/// [`hash_bytes`]'s `2^15.45`. It exists so that a sink which CAN hold eight felts has no excuse
/// to take one.
pub fn hash_bytes_8(data: &[u8]) -> [BabyBear; 8] {
    hash_many_8(&BabyBear::bytes_to_lanes(data))
}

/// The EMPTY-receipt-log domain tag — ASCII `RCE2`, the same 4-byte-tag convention the sibling
/// accumulators use (`FLI2`/`FLN2`/`FLE2` on the cells tree). Lean twin:
/// `ReceiptChain8.rchainEmptyTag`.
pub const RCHAIN_EMPTY_DOMAIN: BabyBear = BabyBear::from_canonical(0x5243_4532 % 2013265921);

/// **THE RECEIPT-LOG ROOT, AT EIGHT LANES** — the single definition of the fold
/// `turn::rotation_witness::iroot` names, and the byte-twin of the Lean keystone
/// [`Dregg2.Lightclient.ReceiptChain8.RChain8Scheme.rchain8`]
/// (`metatheory/Dregg2/Lightclient/ReceiptChain8.lean`), whose
/// `rchain8_binds_or_collides` proves — UNCONDITIONALLY, with no refuted floor — that two logs with
/// equal roots are equal OR a total extractor hands back a genuine collision of this chip.
///
/// ```text
///   root8 := hash_many_8 []                                       -- arity 0, the EMPTY-log root
///   for (i, rh) in log, oldest first:
///       entry8 := hash_bytes_8 rh                                 -- 8 lanes, injective preimage
///       leaf8  := hash_many_8 (i ‖ entry8)                        -- arity 9
///       root8  := hash_many_8 (root8 ‖ leaf8)                     -- arity 16 — the node8 block
/// ```
///
/// Three preimage LENGTHS ride one carrier — 0, 9, 16 — and they are mutually disjoint, so the
/// empty / leaf / node domains separate by length alone with no tag felt. (The Lean MMR this fold
/// was once claimed to realize separates its cons and node cases only by position, both at arity 2.)
///
/// # ⚑ THE NUMBER, DERIVED — and it is COLLISION, not second-preimage
///
/// A receipt-log root is a fold over a log; what an equivocating prover needs is two logs with one
/// root, which is a birthday event over the image.
///
/// ```text
///   log₂ p  = 30.906891                     p = 2013265921
///   image   = p^8       ⇒  8 · 30.906891 = 247.255128 bits
///   collision ≈ 2^(247.255128 / 2) = 2^123.63
/// ```
///
/// **2^123.63.** The second-preimage figure for the same object is ~2^247.3 and is NOT the governing
/// number here; quoting it would be the flattering half of the pair.
///
/// # What this replaced, and what it cost while it stood
///
/// The retired producer was a ZERO-seeded left-leaning chain in which BOTH the leaf and the running
/// root were ONE felt (`hash_many [root, hash_many [i, hash_bytes rh]]`). Two independent ~31-bit
/// waists, and the inner one is the cheaper: `hash_bytes` squeezes a 32-byte receipt hash onto one
/// felt, so two DISTINCT receipts produced a literally identical log entry. Measured at **71,133
/// Poseidon2 evaluations / 0.86 s** on one debug-build core — see
/// `turn/tests/iroot_wide_old_admits_new_rejects.rs`, which builds the colliding pair into two
/// well-formed receipt logs and shows the retired fold ACCEPTING them as one history.
///
/// # The empty-log root is TAGGED, and the obvious spelling was wrong
///
/// It seeds the empty log at `hash_many_8 [RCHAIN_EMPTY_DOMAIN, 0]` rather than at ZERO, so the empty
/// receipt root is a domain-separated image like every sibling accumulator's
/// (`empty_nullifier_root_8`, `empty_commitments_root_8`, `empty_revoked_root_8`) instead of a bare
/// sentinel that aliases them all. That is also what makes the Lean extractor TOTAL — `0 =
/// chipAbsorb8 (…)` names no colliding preimage pair.
///
/// ⚠ **It was first written `hash_many_8(&[])`, matching the Lean `chipAbsorb8 []` and `MMR.lean`'s
/// `bag hash [] = hash []`, and that is DEGENERATE HERE.** [`hash_many_8`] absorbs in rate-4 chunks;
/// an EMPTY input has no chunks, so the permutation never runs and lanes 0..3 come back literally
/// ZERO — a zero sentinel in exactly the lane the wire carries. Caught by
/// `rotation_witness::tests::iroot_binds_the_whole_log`. Arity 2 is an admitted chip arity
/// (`CHIP_ADMITTED_ARITIES = [0,2,3,4,7,11,16]`), so the tag survives the in-circuit cutover.
pub fn receipt_chain_root_8(receipt_hashes: &[[u8; 32]]) -> crate::Faithful8 {
    let mut root: [BabyBear; 8] = hash_many_8(&[RCHAIN_EMPTY_DOMAIN, BabyBear::ZERO]);
    for (position, rh) in receipt_hashes.iter().enumerate() {
        let mut leaf_in = [BabyBear::ZERO; 9];
        leaf_in[0] = BabyBear::new(position as u32);
        leaf_in[1..].copy_from_slice(&hash_bytes_8(rh));
        let leaf = hash_many_8(&leaf_in);

        let mut node_in = [BabyBear::ZERO; 16];
        node_in[..8].copy_from_slice(&root);
        node_in[8..].copy_from_slice(&leaf);
        root = hash_many_8(&node_in);
    }
    crate::Faithful8::from_root8(root)
}

/// **THE canonical felt-domain LIFECYCLE-PAYLOAD hash** — the single composition both the producer
/// (`dregg_turn::rotation_witness::lifecycle_felt`) and the per-cell commitment
/// (`dregg_cell::commitment::v9_lifecycle_felt`) fold into the committed lifecycle limb
/// (`B_LIFECYCLE = 29`), AND the one the in-circuit lifecycle-payload hash gate
/// (`EffectVmEmitRotationV3.lifecyclePayloadHashGate`) recomputes from the LIGHT-CLIENT-KNOWN inputs.
///
/// `Poseidon2(disc ‖ payload_8limbs ‖ at)` over the FELT domain:
///   * `disc`     — the lifecycle discriminant (`u8 0..4`), a single felt (the disc gate also pins it);
///   * `payload_8limbs` — the 32-byte payload hash (`reason_hash` / `death_certificate_hash` /
///     `checkpoint_hash`) split into the SAME 8 felts the light client holds as
///     `bytes32_to_8_limbs(h)` (= the effect's `h8(reason)` view, PI-bound via `effects_hash`);
///   * `at`       — the `sealed_at` / `destroyed_at` / `archived_through` height, a single felt (the
///     turn-header `block_height`, committed at `B_COMMITTED_HEIGHT`, light-client-known).
///
/// REPLACES the prior `hash_bytes(disc ‖ payload_bytes ‖ at_le_bytes)` byte-packed sponge, whose 4-byte
/// packing did NOT match any light-client felt view — so the circuit could not recompute it from known
/// inputs (the SNARK-hostile divergence the refusal `fields_root` openable fix hit). This felt-domain
/// composition is recomputable by a Poseidon2 chip-lookup chain over `[disc] ++ payload_8 ++ [at]`, so
/// the committed limb-29 binding is verifiable WITHOUT re-deriving the cell. `Live` carries no payload
/// (the bare `disc` felt). The `Migrated` arm keeps its richer payload and lives in
/// [`lifecycle_migrated_felt`] — distinct from the light-client movers
/// (cellSeal/cellDestroy/receiptArchive) this gate forces, and faithfully encoded because nothing
/// else binds its caller-chosen `attestation`.
///
/// ⚠ The 8 lanes here are `bytes32_to_8_limbs` of a value the in-circuit gate ALSO holds as those
/// same 8 lanes (`h8(reason)`, PI-bound through `effects_hash`), so this preimage is the light
/// client's view by construction and changing it would be a constraint change, not a Rust one.
/// What it costs is stated where it is paid: the lanes are a `u32 % p` projection, so two payload
/// hashes differing by `p` in a 4-byte chunk commit identically here — acceptable only because
/// these payloads ARE hash images (`reason_hash` / `death_certificate_hash` / `checkpoint_hash`),
/// which the `Migrated` attestation is not.
pub fn lifecycle_payload_felt(disc: u8, payload_hash: &[u8; 32], at: u64) -> BabyBear {
    let mut inputs: Vec<BabyBear> = Vec::with_capacity(10);
    inputs.push(BabyBear::new(disc as u32));
    inputs.extend_from_slice(&crate::effect_vm::bytes32_to_8_limbs(payload_hash));
    inputs.push(BabyBear::new((at & 0x7FFF_FFFF) as u32));
    hash_many(&inputs)
}

/// **THE canonical felt-domain MIGRATED-LIFECYCLE hash** — the `CellLifecycle::Migrated`
/// arm of the committed lifecycle limb (`B_LIFECYCLE = 29`), the ONE definition both
/// twins fold (`dregg_cell::commitment::v9_lifecycle_felt` and
/// `dregg_turn::rotation_witness::lifecycle_felt`). Migrated carries a richer payload
/// (destination id + acceptance attestation + height) than
/// [`lifecycle_payload_felt`]'s single 32-byte hash, and — unlike the cellSeal /
/// cellDestroy / receiptArchive movers — it is under NO in-circuit gate
/// (`EffectVmEmitRotationV3.lifecyclePayloadHashGate` is layered onto those three
/// descriptors only), so this composition is free to be the faithful one.
///
/// ## Why the preimage is 16×u16, not 8×`bytes32_to_8_limbs`
///
/// `attestation` is an **opaque 32-byte blob supplied by the caller** — unlike `to`
/// (a derived cell id) it is not a hash image the migrator cannot choose, and unlike
/// `reason_hash` / `death_certificate_hash` it is not recomputed in-circuit from a
/// PI-bound effect param. This limb is therefore its ONLY binding on the v9 anchor
/// a receipt-only client sees.
///
/// The prior preimage ran both 32-byte values through
/// [`crate::effect_vm::bytes32_to_8_limbs`], a per-4-byte-chunk `u32 % p` projection.
/// `2p = 4026531842 < 2^32`, so for 53.1% of chunk values `v` and `v + p` are DISTINCT
/// bytes with an IDENTICAL lane: a second attestation with a byte-identical preimage,
/// hence a byte-identical committed limb, constructed by one addition and no grind.
///
/// Sixteen little-endian `u16` limbs per 32-byte value (`exact_nullifier_aafi::raw_to_u16_le`,
/// the codec `openable_fields_root::EXACT_FIELDS_VALUE_LIMBS`, `dregg_codec::Limbs16` and
/// `cell::commitment_set::exact_commitment_leaf8` already use) are each `< 2^16 ≪ p`, so
/// NOTHING reduces and the preimage determines all 32 bytes exactly. `migrated_at` rides
/// four u16 limbs for the same reason — the previous `at & 0x7FFF_FFFF` aliased every pair
/// of heights differing by `2^31`.
///
/// ⚠ **The residual, stated plainly:** the OUTPUT is still ONE BabyBear felt. Making the
/// preimage injective converts an O(1) constructed alias into a Poseidon2 collision on a
/// ~31-bit image; it does NOT make the committed limb injective, and cannot — that is the
/// felt-width class (`docs/FINDING-state-field-truncation.md`), not this one.
///
/// Preimage length is 37, so `hash_many`'s length-in-capacity domain separation keeps this
/// disjoint from every [`lifecycle_payload_felt`] preimage (length 10).
pub fn lifecycle_migrated_felt(to: &[u8; 32], attestation: &[u8; 32], at: u64) -> BabyBear {
    use crate::exact_nullifier_aafi::{raw_to_u16_le, u64_to_u16_le};
    let mut inputs: Vec<BabyBear> = Vec::with_capacity(37);
    // The Migrated discriminant (`CellLifecycle::discriminant()` = 2).
    inputs.push(BabyBear::new(2));
    for limb in raw_to_u16_le(*to) {
        inputs.push(BabyBear::new(u32::from(limb)));
    }
    for limb in raw_to_u16_le(*attestation) {
        inputs.push(BabyBear::new(u32::from(limb)));
    }
    for limb in u64_to_u16_le(at) {
        inputs.push(BabyBear::new(u32::from(limb)));
    }
    debug_assert_eq!(inputs.len(), 37);
    hash_many(&inputs)
}

/// Hash a leaf fact (predicate + up to 4 terms encoded as field elements) into a single digest.
/// Each fact is up to 5 field elements; we hash them using the Poseidon2 permutation with leaf domain sep.
/// Terms beyond the provided slice are treated as zero.
pub fn hash_fact(predicate: BabyBear, terms: &[BabyBear]) -> BabyBear {
    let mut state = Poseidon2State::new();
    state.state[0] = predicate;
    if !terms.is_empty() {
        state.state[1] = terms[0];
    }
    if terms.len() > 1 {
        state.state[2] = terms[1];
    }
    if terms.len() > 2 {
        state.state[3] = terms[2];
    }
    if terms.len() > 3 {
        state.state[4] = terms[3];
    }
    // Leaf domain separation (different from node)
    state.state[5] = BabyBear::new(0xFACF); // "fact" marker
    state.state[6] = BabyBear::ONE; // leaf flag

    state.permute();
    state.state[0]
}

/// The Poseidon2 round function expressed as constraints.
/// This provides the intermediate values needed by the AIR to verify the hash.
///
/// Returns all intermediate states (for witness generation).
// crypto index loops kept verbatim
#[allow(clippy::needless_range_loop)]
pub fn poseidon2_trace(input_state: &[BabyBear; WIDTH]) -> Vec<[BabyBear; WIDTH]> {
    let mut trace = Vec::with_capacity(TOTAL_ROUNDS + 1);
    let mut state = Poseidon2State::from_elements(input_state);

    // Initial linear layer
    state.external_linear_layer();
    trace.push(state.state);

    let rc = &*ROUND_CONSTANTS;

    // First half external rounds
    for round in 0..EXTERNAL_ROUNDS / 2 {
        for i in 0..WIDTH {
            state.state[i] += rc[round][i];
        }
        for i in 0..WIDTH {
            state.state[i] = Poseidon2State::sbox(state.state[i]);
        }
        state.external_linear_layer();
        trace.push(state.state);
    }

    // Internal rounds
    for round in 0..INTERNAL_ROUNDS {
        let rc_idx = EXTERNAL_ROUNDS / 2 + round;
        state.state[0] += rc[rc_idx][0];
        state.state[0] = Poseidon2State::sbox(state.state[0]);
        state.internal_linear_layer();
        trace.push(state.state);
    }

    // Second half external rounds
    for round in 0..EXTERNAL_ROUNDS / 2 {
        let rc_idx = EXTERNAL_ROUNDS / 2 + INTERNAL_ROUNDS + round;
        for i in 0..WIDTH {
            state.state[i] += rc[rc_idx][i];
        }
        for i in 0..WIDTH {
            state.state[i] = Poseidon2State::sbox(state.state[i]);
        }
        state.external_linear_layer();
        trace.push(state.state);
    }

    trace
}

#[cfg(test)]
mod tests {
    use super::*;

    /// THE ANTI-LAUNDERING TEST for the faithful 8-felt digest: the 8 outputs must be 8 GENUINELY
    /// distinct, input-dependent felts — not `[0]×8`, not a replicated single squeeze. (a) the 8
    /// outputs are pairwise-distinct for a generic input; (b) flipping ANY single input felt changes
    /// ALL 8 outputs (avalanche); (c) the wide digest distinguishes near-collisions that a 1-felt
    /// digest cannot promise.
    #[test]
    fn hash_many_8_is_eight_distinct_avalanching_felts() {
        let input: Vec<BabyBear> = (1u32..=10).map(BabyBear::new).collect();
        let out = hash_many_8(&input);

        // (a) pairwise-distinct — catches a laundered `[0]×8` widening.
        for i in 0..8 {
            for j in (i + 1)..8 {
                assert_ne!(
                    out[i], out[j],
                    "outputs {i} and {j} collide — not 8 distinct felts"
                );
            }
        }
        // and not the degenerate all-zero / all-equal output.
        assert!(out.iter().any(|&x| x != out[0]) || out[0] != BabyBear::ZERO);

        // (b) avalanche: flipping any one input felt changes ALL 8 outputs (each output depends on
        // the whole input — a `[0]×8` or a final-felt-only widening would fail this).
        for k in 0..input.len() {
            let mut flipped = input.clone();
            flipped[k] += BabyBear::new(1);
            let out2 = hash_many_8(&flipped);
            for i in 0..8 {
                assert_ne!(
                    out[i], out2[i],
                    "flipping input {k} left output felt {i} unchanged — not full-input-dependent"
                );
            }
        }

        // (c) near-collision: two inputs differing in ONLY the last (high) felt produce digests that
        // differ — and the FULL 8-felt digest differs, the property the light-client commitment needs.
        let mut hi = input.clone();
        *hi.last_mut().unwrap() += BabyBear::new(1);
        let out_hi = hash_many_8(&hi);
        assert_ne!(
            out, out_hi,
            "a high-position change must move the 8-felt digest"
        );
    }

    /// **THE 8-FELT CHAIN PRIMITIVE TEETH** (Phase B-ROTATION) — the standalone proofs that
    /// `wire_commit_8` is a GENUINE 8-felt digest (~124-bit collision), NOT a laundered
    /// 1-felt-chain-with-wide-final-squeeze.
    #[test]
    fn single_perm_compress_is_chip_faithful_and_avalanching() {
        // ONE permutation, 8 distinct lanes, full-input dependence (the chip-faithful contract).
        let ins: Vec<BabyBear> = (1u32..=11).map(BabyBear::new).collect();
        let out = single_perm_compress(&ins);
        for i in 0..8 {
            for j in (i + 1)..8 {
                assert_ne!(
                    out[i], out[j],
                    "compress lanes {i},{j} collide — not 8 distinct felts"
                );
            }
        }
        // avalanche: flipping ANY one of the 11 inputs moves ALL 8 output lanes.
        for k in 0..ins.len() {
            let mut f = ins.clone();
            f[k] += BabyBear::new(1);
            let o2 = single_perm_compress(&f);
            for i in 0..8 {
                assert_ne!(
                    out[i], o2[i],
                    "flipping input {k} left lane {i} fixed — not full-dep"
                );
            }
        }
    }

    #[test]
    fn wire_commit_8_collision_distinguishing_tooth() {
        // COLLISION-DISTINGUISHING: two limb vectors differing ONLY in a HIGH position (the last
        // pre-iroot limb — the fields_root sub-limb's place) produce 8-felt commits differing in
        // ≥ 1 felt. A 1-felt commitment promises only ~31-bit separation here; the 8-felt digest
        // separates them with ~124-bit collision resistance.
        let limbs: Vec<BabyBear> = (0u32..37).map(|i| BabyBear::new(500 + i)).collect();
        let iroot = BabyBear::new(7);
        let base = wire_commit_8(&limbs, iroot);
        let mut hi = limbs.clone();
        *hi.last_mut().unwrap() += BabyBear::new(1); // a high-position one-felt change
        let moved = wire_commit_8(&hi, iroot);
        assert_ne!(
            base, moved,
            "a high-limb change must move the 8-felt commitment"
        );
        assert!(
            (0..8).any(|i| base[i] != moved[i]),
            "at least one of the 8 committed felts must differ"
        );
        // the iroot is bound too.
        assert_ne!(
            base,
            wire_commit_8(&limbs, BabyBear::new(8)),
            "iroot is bound"
        );
    }

    #[test]
    fn wire_commit_8_intermediate_carrier_tooth() {
        // INTERMEDIATE-CARRIER: a difference in an EARLY pre-limb (folded MID-CHAIN, never near
        // the final squeeze) propagates to the published 8-felt commit — because the carrier is
        // 8-wide THROUGHOUT, not just at the final squeeze. (A 1-felt-chain-with-wide-final-
        // squeeze launders an early difference through a 31-bit waist; this proves there is none.)
        let limbs: Vec<BabyBear> = (0u32..37).map(|i| BabyBear::new(500 + i)).collect();
        let iroot = BabyBear::new(7);
        let base = wire_commit_8(&limbs, iroot);
        // move limb 5 — folded in the SECOND chain group, deep before the final squeeze.
        let mut early = limbs.clone();
        early[5] += BabyBear::new(1);
        let moved = wire_commit_8(&early, iroot);
        assert_ne!(
            base, moved,
            "an early mid-chain limb change must reach the published commit"
        );
        // and avalanche through the whole 8-felt digest (no 31-bit waist that drops bits).
        for i in 0..8 {
            assert_ne!(
                base[i], moved[i],
                "early-limb change left committed felt {i} unchanged"
            );
        }
    }

    /// The 8-felt chain is NOT the 1-felt chain's squeeze tacked on — moving a limb the 1-felt
    /// chain happens to leave near-fixed still moves the wide digest (the floor this phase closes).
    #[test]
    fn wire_commit_8_is_not_a_laundered_widening() {
        let limbs: Vec<BabyBear> = (0u32..37).map(|i| BabyBear::new(11 * i + 3)).collect();
        let iroot = BabyBear::new(99);
        let c = wire_commit_8(&limbs, iroot);
        // every single-limb flip moves the wide commit (binds all 37 limbs + iroot).
        for k in 0..37 {
            let mut m = limbs.clone();
            m[k] += BabyBear::new(1);
            assert_ne!(
                c,
                wire_commit_8(&m, iroot),
                "limb {k} must be bound by the 8-felt commit"
            );
        }
    }

    #[test]
    fn poseidon2_different_inputs_different_outputs() {
        let a = [
            BabyBear::new(1),
            BabyBear::new(2),
            BabyBear::new(3),
            BabyBear::new(4),
        ];
        let b = [
            BabyBear::new(5),
            BabyBear::new(6),
            BabyBear::new(7),
            BabyBear::new(8),
        ];
        assert_ne!(hash_4_to_1(&a), hash_4_to_1(&b));
    }

    #[test]
    fn poseidon2_non_zero_output() {
        let input = [BabyBear::ZERO; 4];
        let h = hash_4_to_1(&input);
        // With round constants, even zero input should produce non-zero output
        assert_ne!(h, BabyBear::ZERO);
    }

    #[test]
    fn hash_many_works() {
        let inputs: Vec<BabyBear> = (1..=10).map(|i| BabyBear::new(i)).collect();
        let h = hash_many(&inputs);
        assert_ne!(h, BabyBear::ZERO);
    }

    #[test]
    fn poseidon2_trace_consistency() {
        let mut input = [BabyBear::ZERO; WIDTH];
        input[0] = BabyBear::new(10);
        input[1] = BabyBear::new(20);
        input[2] = BabyBear::new(30);
        input[3] = BabyBear::new(40);
        let trace = poseidon2_trace(&input);
        // Should have TOTAL_ROUNDS + 1 states
        assert_eq!(trace.len(), TOTAL_ROUNDS + 1);
        // First state is after initial linear layer
        let mut expected_init = Poseidon2State::from_elements(&input);
        expected_init.external_linear_layer();
        assert_eq!(trace[0], expected_init.state);
        // Last state matches direct permutation
        let mut state = Poseidon2State::from_elements(&input);
        state.permute();
        assert_eq!(*trace.last().unwrap(), state.state);
    }

    #[test]
    fn sbox_power_7() {
        // x^7 for x=2: 128
        let x = BabyBear::new(2);
        let y = Poseidon2State::sbox(x);
        assert_eq!(y.0, 128);
    }

    #[test]
    fn hash_bytes_different_inputs() {
        let h1 = hash_bytes(b"foo");
        let h2 = hash_bytes(b"bar");
        assert_ne!(h1, h2);
    }

    #[test]
    fn hash_bytes_32_byte_input() {
        let commitment = [0xAB_u8; 32];
        let h = hash_bytes(&commitment);
        assert_ne!(h, BabyBear::ZERO);
    }

    /// Known-answer test vector for Poseidon2 permutation over BabyBear width-16.
    ///
    /// Input: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
    /// This vector is computed from the Plonky3-compatible round constants
    /// (RC_EXT_INIT, RC_INTERNAL, RC_EXT_FINAL) and internal diagonal (INTERNAL_DIAG)
    /// defined in this module. Any change to these parameters will break this test,
    /// which is the intended behavior: it catches accidental parameter drift.
    #[test]
    fn poseidon2_known_answer_vector() {
        // Input: sequential field elements [0..15]
        let mut input = [BabyBear::ZERO; WIDTH];
        for i in 0..WIDTH {
            input[i] = BabyBear::new(i as u32);
        }
        let mut state = Poseidon2State::from_elements(&input);
        state.permute();

        // Expected output (frozen from implementation with Plonky3-sourced parameters)
        let expected: [u32; 16] = [
            1906786279, 1737026427, 1959749225, 700325316, 1638050605, 1021608788, 1726691001,
            1761127344, 1552405120, 417318995, 36799261, 1215172152, 614923223, 1300746575,
            957311597, 304856115,
        ];

        for i in 0..WIDTH {
            assert_eq!(
                state.state[i].0, expected[i],
                "Poseidon2 permutation output mismatch at position {i}: \
                 got {}, expected {}",
                state.state[i].0, expected[i]
            );
        }
    }

    /// Known-answer test for hash_4_to_1 compression function.
    /// This is the core primitive used in the 4-ary Merkle tree.
    #[test]
    fn hash_4_to_1_known_answer() {
        let h = hash_4_to_1(&[
            BabyBear::new(1),
            BabyBear::new(2),
            BabyBear::new(3),
            BabyBear::new(4),
        ]);
        assert_eq!(
            h.0, 1163579196,
            "hash_4_to_1([1,2,3,4]) known-answer mismatch: got {}, expected 1163579196",
            h.0
        );
    }

    /// Cross-implementation known-answer test (conformance KAT).
    ///
    /// This is the *genuine* conformance check, not a frozen self-snapshot: it
    /// runs the SAME input through BOTH dregg's `Poseidon2State::permute` AND
    /// Plonky3's independently-audited `default_babybear_poseidon2_16()`
    /// (`p3-baby-bear` rev 82cfad73 pinned in the workspace Cargo.toml), then
    /// asserts the full 16-element output state is byte-for-byte identical.
    ///
    /// Both implementations use the standard BabyBear Poseidon2 instance:
    ///   - width 16, S-box x^7, R_F = 8 (4 + 4), R_P = 13
    ///   - external round constants BABYBEAR_POSEIDON2_RC_16_EXTERNAL_{INITIAL,FINAL}
    ///   - internal round constants BABYBEAR_POSEIDON2_RC_16_INTERNAL
    ///   - internal diagonal V = [-2, 1, 2, 1/2, 3, 4, -1/2, -3, -4,
    ///                            1/2^8, 1/4, 1/8, 1/2^27, -1/2^8, -1/16, -1/2^27]
    ///
    /// dregg's constants (RC_EXT_INIT / RC_EXT_FINAL / RC_INTERNAL / INTERNAL_DIAG)
    /// are transcribed from these exact Plonky3 tables, so a match establishes real
    /// conformance to the reference. A mismatch would be a critical finding (a
    /// constant/round/matrix divergence in the crypto TCB).
    ///
    /// Note: Plonky3's `permute_mut` applies the initial external linear layer
    /// then the rounds, identical to dregg's `permute`, so the raw permutation is
    /// the correct unit of comparison (no domain-separation padding involved).
    #[test]
    fn poseidon2_plonky3_cross_check_kat() {
        use crate::field::BABYBEAR_P;
        use crate::plonky3_prover::{from_p3, to_p3};
        use p3_baby_bear::BabyBear as P3BabyBear;
        use p3_baby_bear::default_babybear_poseidon2_16;
        use p3_symmetric::Permutation;

        let perm = default_babybear_poseidon2_16();

        // Test vectors covering edge cases + structured + pseudo-random inputs.
        // Each is 16 canonical u32 values (already < BABYBEAR_P).
        let p = BABYBEAR_P;
        let vectors: Vec<[u32; WIDTH]> = vec![
            // all-zeros
            [0; WIDTH],
            // all-ones
            [1; WIDTH],
            // sequential 0..15
            std::array::from_fn(|i| i as u32),
            // sequential 1..16
            std::array::from_fn(|i| (i as u32) + 1),
            // all p-1 (largest canonical value)
            [p - 1; WIDTH],
            // alternating 0 / p-1
            std::array::from_fn(|i| if i % 2 == 0 { 0 } else { p - 1 }),
            // fixed pseudo-random vector (xorshift-derived, seed 0xD2E66, reduced mod p)
            {
                let mut s: u32 = 0xD2E66;
                std::array::from_fn(|_| {
                    s ^= s << 13;
                    s ^= s >> 17;
                    s ^= s << 5;
                    s % p
                })
            },
            // second fixed pseudo-random vector (seed 0x5EED1)
            {
                let mut s: u32 = 0x5EED1;
                std::array::from_fn(|_| {
                    s ^= s << 13;
                    s ^= s >> 17;
                    s ^= s << 5;
                    s % p
                })
            },
            // powers of two (exercises the inverse-power-of-2 diagonal entries)
            std::array::from_fn(|i| 1u32 << (i % 31)),
        ];

        for (vi, raw) in vectors.iter().enumerate() {
            // dregg permutation
            let mut dregg_input = [BabyBear::ZERO; WIDTH];
            for i in 0..WIDTH {
                dregg_input[i] = BabyBear::new(raw[i]);
            }
            let mut dregg_state = Poseidon2State { state: dregg_input };
            dregg_state.permute();

            // Plonky3 reference permutation on the identical input
            let mut p3_input: [P3BabyBear; WIDTH] =
                std::array::from_fn(|i| to_p3(BabyBear::new(raw[i])));
            perm.permute_mut(&mut p3_input);

            // Assert byte-for-byte (canonical-value) equality across all 16 lanes.
            for i in 0..WIDTH {
                let dregg_out = dregg_state.state[i].canonical_val();
                let p3_out = from_p3(p3_input[i]).0;
                assert_eq!(
                    dregg_out, p3_out,
                    "Poseidon2 conformance MISMATCH on vector {vi} at lane {i}: \
                     dregg={dregg_out}, plonky3={p3_out} (input[{i}]={})",
                    raw[i]
                );
            }
        }
    }
}
