/-
# Compiler — the arithmetization spine (ATLAS §7).
-/
import Compiler.Placeholder  -- carve marker: syntactic-leaf IR, fold_unique, seqDescr, descriptor + codec
import Compiler.Signature    -- N3: abstract signatures, Term (= WType), fold_unique, agree_by_initiality, the syntactic-leaves-forced obligation
import Compiler.Air  -- the arithmetization DSL (derived): circuit⟺executor by initiality (N3), the first gadget; [AIR-poseidon]/[AIR-membership] the rungs toward a note-spend
import Compiler.AirFlatten  -- [AIR-flatten] CLOSED: nested expressions → degree-≤2 gate systems with aux wires, the flatten a fold; wire-forcing refinement (sound+complete+unique) → gate system ⟺ executor
import Compiler.DialectBundle  -- typed heterogeneous ports/fingerprints and an assurance meet that prevents native/floor/unclosed artifacts from masquerading as proof-verified receipts
import Compiler.AirRange  -- [AIR-range] the bit-decomposition range gadget: k boolGadgets + recomposition as a ConstraintSystem; correct (iff) + bounds (cast of n < 2^k) + val_lt (ZMod p, 2^k ≤ p — the lift CLOSED) + complete (every n < 2^k accepted)
import Compiler.AirBignum  -- fixed-width radix-2^k addition over Theory.Bignum: emitted range/carry constraints, exact integer soundness, overflow rejection
import Compiler.AirModularView  -- exact modular-view AIR plus wide fixed-modulus scalar multiplication; FHEgg q0×24-bit quotient bounds are proved, while the signed/compressed equation frontend remains explicit
import Compiler.FheArithmetic  -- BFV linear/query/directed-rescale and TFHE modulus-switch/initial-rotation arithmetic; native/cryptographic refinements remain explicit
import Compiler.FheInfer  -- complete saved nonlinear Infer source dependencies; runtime trust boundaries remain explicit
import Compiler.BignumKernelABI  -- Lean-owned versioned call envelope: metadata schedules native arithmetic only; acceptance remains exactly descriptorHolds
import Compiler.BfvAllModuliKernelCalls  -- FHEgg q0/q1/q2 fixed-modulus calls in deployed order, with exact 10/10/11 radix-64 layouts and descriptorHolds acceptance
import Compiler.BfvInputValidity  -- one committed owner witness binds selector/table validity, bounded BFV inputs, public relation identifiers, and all 384 modulus-major kernel calls
import Compiler.BfvSignedAccumulatorAir  -- exact radix-64 weighted positive/negative accumulators over that same witness and accepted quotient call imply numerator = q * centered quotient
import Compiler.BfvReceiptClause  -- one committed BFV batch plus checked returned buffers yields all 384 exact integer equations; the native producer remains semantically opaque
import Compiler.BfvProofController  -- deterministic BFV statement/receipt framing over opaque bytes; proof-codec/suite/controller pins stay zero and the succinct suite is deliberately uninstantiated
import Compiler.BfvCompressedEquation  -- audited FHEgg 12,435-coordinate/384-row schema and the first exact q0 shifted-quotient AIR join; the full signed accumulator and Lean-owned transcript control stay explicit
import Compiler.WideDigestAir  -- [AIR-wide-digest] WDG1/domain/9-limb encoding pinned through emit; canonicality and 248-bit capacity proved; sponge schedule, concrete permutation, native-output checks, and [COMMIT-CR] remain explicit
import Compiler.WideDigestByteDecodeAir  -- raw four-byte little-endian limbs are range-checked and proved < BabyBear before field recomposition; raw p is universally rejected
import Compiler.Ext6Conformance  -- BabyBear[u]/(u^6−31) irreducible with finrank six; the six-lane multiplication formula and known vectors are proved for unverified native compute to reproduce
import Compiler.GateMleExt6  -- emitted descriptor residuals lifted and gamma-batched in Ext6, with exact MLE sumcheck rounds/terminal; the succinct factored-selector commitment opening is the sole remaining gate-oracle seam
import Compiler.GateFactoredExt6 -- seven sparse selector operands give the exact gamma-batched descriptor claim, degree-two rounds, public trace functionals, and a sharp fresh-eta aggregation bound
import Compiler.GateTraceRelationExt6 -- extends eta aggregation to the entire public prefix and zero padding, and proves the exact Ext6 subfield-evaluation bound behind sampled base-limb checks
import Compiler.NextgenLightClientPublicInputs -- exact current binary light-client public schema: consuming decoder round-trip/injectivity, canonical BabyBear cells, exact framed length, and public-prefix uniqueness; handwritten native code remains unverified
import Compiler.TypedAuthorizationRequestCodec  -- `LawfulCodec (Request .object)` on the landed `StreamCodec` prefix framework: one of the three codecs a Hyperdocument `Config` demands, with teeth that the encoding separates target and effects digest
import Compiler.HyperdocumentCodec  -- the Hyperdocument value type tree on the wire: identifiers, finite tags, records, atom kinds, embeds, and stable ranges, all on `StreamCodec`; the remaining half of what a `Config` demands
import Compiler.HyperdocumentContentPageMaterializer  -- bounded versioned content pages retain exact links, routing, canonical sparse projection, and cSHAKE roots
import Compiler.HyperdocumentEventPageMaterializer  -- bounded versioned causal-event pages retain exact entries, sparse-log projection, and cSHAKE roots
import Compiler.CredentialAuthorityPageMaterializer  -- bounded policy/revocation pages project exact committed authority roots, epochs, addresses, and membership
import Compiler.BoundedPageExtensionCatalog  -- one canonical catalog pins all bounded page schemas/codecs/controllers/domains and a cross-page link bundle
import Compiler.BoundedPageCellRegistry  -- the three exact framed page materializers cross a dependent heterogeneous create/delete registry with no casts
import Compiler.BoundedPageSchemaUpgrade  -- V2 page codecs/controllers preserve typed projections while changing exact canonical bytes under an authorized migration
import Compiler.HyperdocumentIndexPageMaterializer  -- bounded backlink/range index rows have a versioned framed codec, cSHAKE root, and exact causal projection
import Compiler.DeployedCellRegistry  -- concrete dependent registry packs the four deployed cell kinds and witnesses create/delete rejection teeth without casts
import Compiler.FiniteSparseMaterializerAudit  -- exact seven-schema census: all accepted/non-vacuous, with four inhabitation-only codecs distinguished from three production-pinned page codecs
import Compiler.CredentialAuthorityPolicyRegistry  -- the bounded authority page drives exact compiled-policy selection and a root-guarded durable intent
import Compiler.SemanticTurnReceiptDescriptor -- Lean-authoritative semantic receipt declaration -> AIR -> emitted first-order artifact; downstream native code only reads the generated descriptor
import Compiler.SemanticManifest -- content-addressed first-order semantic ABI, carrier profiles, named bridges, closed dialect-clause registry, and history/admission bindings
import Compiler.SemanticArtifactBundle -- canonical Lean-generated manifest/declaration/phase artifact with JSON writer; contains data and plans, never native verifier semantics
import Compiler.DeclaredEffectArtifact -- first-order effect artifact projected from the target-indexed Theory.EffectDeclaration, including the concrete v1 account move
import Compiler.DeclaredActionBytes -- versioned canonical create/write/move batches compile fail-closed into the accepted action language
import Compiler.DeclaredHyperedgeArtifact -- flat joint turns emit the complete ordered request/effect family and presentation-root pins; no call forest or opaque witness codec is invented
import Compiler.NativeWorkProfiles -- Lean-owned closed native work/codec catalog and benchmark schedules; generated workers still return only fallible bytes
import Compiler.NativeKernelPlan -- closed arithmetic/hash/transform work plans; arbitrary native runners may block with opaque errors or return bounded data, but cannot choose continuation or acceptance
import Compiler.MinidreggV1ArithmeticWork -- concrete zero-add arithmetic clause/work item: a successful native buffer is admitted only by the generic Lean checker; native failure blocks
import Compiler.ArithmeticNativeDeployment -- clause 406 is an artifact-authenticated generated bytes/error work item whose fixed candidate is decoded and certified only by Lean
import Compiler.DialectClauseDispatch -- a manifest clause is dispatchable only with its exact Lean controller; native failure blocks and only that controller checks the reply
import Compiler.NativeGlueGen -- deterministic data-only Rust DTO/dispatch text generated from the canonical Lean artifact; no native semantics or acceptance
import Compiler.MinidreggV1Artifact -- concrete v1 declaration bundle and Lean-emitted canonical JSON payload; bridge/clause records are requirements, not implementation claims
import Compiler.MinidreggV1NativeGlue -- writes the data-only native constants/DTO/buffer-dispatch surface from the concrete Lean artifact
import Compiler.Logup256ReceiptClause -- canonical Boolean indices force unit-vector incidence, LogUp pushforward, and exact indexed evaluation; PCS/CR/ROM remain explicit premises
import Compiler.AdditiveFriReceiptClause -- rate/basis/root schedule plus local additive acceptance, separated from the exact far-word UD probability certificate
import Compiler.SemanticController -- arbitrary native oracle may return bounded data only; Lean owns authorization, challenge/order, descriptor checks, and the sole Verified token
import Compiler.TranscriptController -- Lean-owned phased transcript program: native replies are data, challenges and query order are derived internally, and only the Lean checker can accept
import Compiler.AuthenticatedColumnPlan -- typed columns, derived roots, one roots-before-challenges transcript, checked opaque work/openings/representation edges, and a trace-indexed terminal attestation
import Compiler.AuthenticatedColumnLogupBridge -- a terminal attestation's reflected LogUp statement and authentic first-draw root prefix discharge canonical linkage, Tower arithmetic, root binding, and exact indexed evaluation; PCS/CR/ROM remain explicit
import Compiler.Tower256CshakeMerkleController -- shared Lean-selected cSHAKE framing, exact logarithmic cube-Merkle openings, Tower256 codec/profile obligations, and arbitrary-native-reply exactness; CR/ROM/PCS remain explicit
import Compiler.Sp800185Cshake256 -- exact Lean Keccak-f[1600] + SP 800-185 framing instantiate the controller's proved 32-byte cSHAKE256 API; no CR/ROM claim
import Compiler.Sp800185Cshake256Conformance -- executable NIST SP 800-185 and FIPS 202 vectors remain continuously checked without entering the controller API surface
import Compiler.BinaryTower256Profile -- inhabits the Tower256 controller profile with Lean's binaryTower 8 and exact 32-byte codec; no native representation claim
import Compiler.Tower256NativeByteBoundary -- arbitrary native Tower256 compute returns bytes only; Lean's exact Fan--Paar decoder plus a reflected Lean checker are the sole path to an accepted semantic value
import Compiler.Tower256CshakeMerkleBinding -- exact framed leaf/node XOF collision event; accepted unequal openings at one root/index reduce to a collision, with exact-depth paths and cryptographic event price left explicit
import Compiler.Tower256ConcreteBackend -- one shared Tower256/cSHAKE/Merkle backend with exact Lean codecs and domain pins; CR/ROM remain explicit
import Compiler.Tower256LogupControllerPlan -- four LogUp roots before round challenge, additive checkpoint before query challenge, exact Merkle openings, opaque fallible Tower work, and reflected Lean final semantics
import Compiler.Tower256LogupAcceptedRun -- every verified execution of that exact plan retains its reflected statement and four-root prefix, yielding indexed evaluation from explicit PCS/CR/ROM judgments
import Compiler.Tower256LogupClauseDispatch -- extension-local clause-404 dispatch turns exactly two keyed opaque byte replies into the existing Lean-verified execution; base V1 remains empty
import Compiler.Tower256LogupExtensionDeployment  -- nonzero versioned extension pins and concrete shared-backend inputs inhabit the two-call byte controller while base V1 stays empty
import Compiler.Tower256AdditiveFriController -- exact cSHAKE-derived additive-FRI control over opaque proof bytes; Lean alone decodes and accepts
import Compiler.Tower256AdditiveFriRawController -- the same additive checker with NO universal `PositionBinding`: an unequal accepted opening is retained and extracts a path-specific framed cSHAKE collision instead of vanishing
import Compiler.Tower256AdditiveFriRawDeployment  -- concrete raw PCS levels, statement codecs, and opaque-byte verifier witnesses inhabit the collision-retaining deployment path
import Compiler.Ext6GateProofController -- descriptor-bound Ext6 gate transcript control over opaque bytes; PCS/LDT/ROM security remains explicit
import Compiler.Ext6GateProofDeployment  -- nonzero pinned Ext6 deployment carriers and reflected control, with all eight security reductions still explicit
import Compiler.Ext6GateProofPositiveRun  -- one causal five-round receipt for the 23-residual deployment reaches canonical bytes and Lean acceptance; no security residual is fabricated
import Compiler.FramedWalRecoveryController  -- opaque recovery bytes are framed, checked, and replayed only by Lean before a recovered snapshot can exist
import Compiler.FramedWalRecoveryDeployment  -- recovery work and controller enter an extension deployment without pretending to be native V1 semantics
import Compiler.ComposableDeploymentManifest -- deployment clauses are projected from actual controller entries; gated/reserved clauses do not enter by declaration alone
import Compiler.SparseAuthenticatedStateLogupBridge -- exact sparse ROM/RAM/append buses compile to canonical Tower256 lookup indices while retaining Twist-style state continuity and explicit PCS/CR/ROM premises
import Compiler.SparseEqualityWorkProfile -- Lean-owned dense/sparse equality-functional benchmark schedule, with the common MLE target proved before opaque native timing
import Compiler.AirHash  -- [AIR-poseidon] the hash-permutation gadget: parameterized Poseidon2-style rounds (add-rc, S-box x^α full/partial, linear layer) as DSL terms; permGadget_eval (circuit ⟺ executor, all R rounds) + hashConstraint (nullifier ≐ hash(note), iff + teeth + complete); [AIR-poseidon-params] the deployed constants, [COMMIT-CR] the crypto floor
import Compiler.AirMembership  -- [AIR-membership] the Merkle-membership gadget: mux-selected compression (permGadget reused) folded up a path as one DSL term + boolGadget per direction bit; membership_correct (iff, every depth) + membership_meaning (∃ path ⟺ member, sound+complete) + teeth (root & bits); [COMMIT-CR]/[AIR-poseidon-params] inherited — the last note-spend gadget before [PRIVATE-TURN-air] composition
import Compiler.NoteSpend  -- [PRIVATE-TURN-air] CLOSED at the arithmetization level: the shielded note-spend = rangeGadget ++ hashConstraint (nullifier) ++ hashConstraint (commitment) ++ membershipGadget over ONE shared witness; noteSpend_correct (iff = the 3 gadget meanings conjoined) + noteSpend_binds (accepted ⟹ ValidSpend) + noteSpend_meaning (∃ asg ⟺ ∃ note, ValidSpend — the relation loom_zk_argument proves knowledge of); HIDING is Loom/ZK's layer, [COMMIT-CR]/[AIR-poseidon-params] the floors
import Compiler.NoteSpendProofController  -- canonical sealed note-spend statements and opaque proof bytes are decoded and accepted only by Lean; PCS/PoK/CR/ROM/hiding remain suite obligations
import Compiler.AdmissionAir  -- [ADMISSION-air] the kernel's GATED ADMISSION (Verb = admission × footprint), derived: admissionGadget = capabilityGadget (hashConstraint + membershipGadget — the cap hashes into the committed authority set) ++ footprintGadget (boolGadget flags + frame terms (1−fᵢ)·(postᵢ−preᵢ) — undeclared cells stand still, touched ⊆ declared) ++ targetGadget (fᵢ·(cellᵢ−target) — declared cells ARE the capability's target, the ι=1 coupling); admission_correct (iff = AdmissionHolds, statement-first) + admission_authorizes (∃-form memberAtDepth soundness) + gates_touch/covers teeth + admission_complete; keystones ZMod 7/13 with per-gadget attribution (rights-escalation forgery rejected both ways; FULL authority still rejected on an out-of-footprint touch); the Kernel correspondence (Hyperedge verbs, caps table) in PROSE — residual [ADMISSION-kernel-bridge] (Assurance-side identification with the kernel's admission predicate, rights decode, global frame, ι=N disjointness)
import Compiler.Emit  -- Lean-owned first-order ConstraintDescriptor plus unconditional emit_faithful/emit_accepts_iff; native code may return candidate buffers only, and a future Lean-emitted online plan must check descriptorHolds before constructing acceptance
import Compiler.EmitShare  -- [EMIT-share] CLOSED: hash-consing CSE on the descriptor, a PASS with its own faithfulness theorem — cse (one walk: wire-substitution + signature table, Std.HashMap-backed); cse_holds (forward, UNCONDITIONAL, same witness) + holds_of_cse_holds (backward under SSA, witness through cseSubst) + cse_faithful (satisfiability-equivalence); the SSA hypothesis is REAL (backward is FALSE without it — counterexamples in the header) and DISCHARGED at the deployed shape by emit_ssa (inputs-below-output from flattenSystem_scoped + allocation order made explicit); cse_emit_accepts_iff re-closes the seam THROUGH the CSE (the prover on the SMALL descriptor proves the SAME statement); note-spend measured 2,696,666 → 220 gates (compiled #eval, ≈12,258×); residual [EMIT-share-compact] (wire renumbering + dead-gate sweep; structural sharing only — no algebraic identities)
import Compiler.EmitSerialize  -- [PROVER-serialize] CLOSED: the descriptor wire-format concretized (JSON, constants as canonical ZMod.val, modulus stamped) + reader/writer over ZMod p, round-trip checked at build time with teeth; [PROVER-field] BabyBear p = 2^31−2^27+1 proved prime (norm_num) so the emit-path theorems apply verbatim; the 4-bit rangeGadget emitted over BabyBear as prover/testdata/demo_descriptor.json (satisfiable at x=13 + teeth at x=14, decided) — the conformance anchor for the UNVERIFIED Rust prover/ crate, which only ever reads
import Compiler.SumcheckVerifierAir  -- [RECURSE-verifier] first component: the sumcheck VERIFIER as a ConstraintSystem (round checks g_i(0)+g_i(1) ≐ chain_i with chain the values-form scChain — the (1−r)·g(0)+r·g(1) fold — + the final oracle-wire check); sumcheckVerifier_correct (iff = SumcheckVerifierAccepts, statement-first) + emit_accepts_iff consumed on the gadget (the recursion apex: "the verifier accepted" is itself an emitted, Loom-provable statement); keystones ZMod 7/13 (honest MLE-of-AND transcript accepted, claim/final wires FORCED, tampered message & tampered challenge rejected with per-check attribution); residuals [RECURSE-sumcheck-bridge] (the Loom.SumcheckAccepts identification, Assurance-side) + [RECURSE-verifier] (FS challenge-binding via AirHash, oracle-binding via AirMembership, FRI-query gadget)
import Compiler.FriQueryVerifierAir  -- [RECURSE-verifier] last major component: the FRI query's fold-consistency check as a ConstraintSystem (per round: twiddle-inverse tw·twoX ≐ 1 — the fold's division WITNESSED, a mul gate — + fold-consistency next ≐ (lo+hi)·half + β·(lo−hi)·tw, Loom.Proximity.fold's twiddle form; + the final low-degree check); friQueryVerifier_correct (iff = FriQueryAccepts, statement-first) + _correct_div (under 2·half=1 acceptance IS the divided Loom-fold equations) + recursiveVerifierPair_correct (sumcheck ++ FRI-query = both accept, the apex composition step) + emit_accepts_iff consumed on the gadget; keystones ZMod 7/13 (honest 2-round fold of X+1 accepted incl. the chained wiring next₀ = lo₁, tampered opening & fake twiddle rejected with per-check attribution, opened/twiddle/final wires FORCED quantified); residuals [RECURSE-fri-bridge] (the Loom.fold identification, Assurance-side) + [RECURSE-verifier] (the wire-sharing composition: FS challenges via AirHash, openings via AirMembership, twoX via the index's domain point)
import Compiler.FiatShamirAir  -- [RECURSE-verifier] the Fiat–Shamir challenge BINDING: fsBindingGadget = one AirHash hashTerm per squeeze, the absorb–squeeze chain carried by wire-sharing (prev challenge wire = slot 0 of the next block); fsBinding_correct (iff = FsBound: every challenge wire ≐ the chain hash of its transcript PREFIX — round-local hash equations ⟺ global chain, one induction) + teeth + complete; boundVerifier = fsBinding ++ sumcheckVerifier ++ friQueryVerifier (boundVerifier_correct = the 3 meanings conjoined; boundVerifier_challenges_bound: with chal/β wires SHARED with squeeze wires, acceptance FORCES derived challenges — the composed AIR is a SELF-CONTAINED non-interactive verifier) + emit_accepts_iff consumed on the composed demo; keystones ZMod 7/13 (honest derived-challenge transcripts accepted; the free-challenge forgery ACCEPTED by the unbound pair and REJECTED by the binding with per-squeeze attribution; ZMod 7 challenge wires FULLY determined, 49-case quantified); residuals [RECURSE-merkle-bind] (openings/roots via AirMembership — the last composition piece) + [RECURSE-fs-sponge] (deployed sponge mode) + [RECURSE-fs-bridge] (the Loom FS identification, Assurance-side) + [FS-oracle] floor
import Compiler.MerkleBindAir  -- [RECURSE-merkle-bind] CLOSED: openingBindingGadget = one AirMembership membershipGadget per FRI round (opened wire = leaf, commitment-root wire = root; pair-per-leaf: hi IS lo's first path sibling by wire-sharing); openingBinding_correct (iff = OpeningsBound, statement-first) + _member (every accepting asg's openings are memberAtDepth members) + _complete + _meaning (∃ asg ⟺ ∀ k member, both ways); fullVerifier = boundVerifier ++ openingBindingGadget (fullVerifier_correct = FS-bound ∧ sumcheck ∧ FRI ∧ Merkle-bound; fullVerifier_binds: at shared wiring NOTHING on the proof-carrying wires is free — derived challenges + member openings) + emit_accepts_iff consumed: the WHOLE light-client verifier is ONE emitted Loom-provable statement (a proof verifies a proof); keystones ZMod 7/13 (ZMod 7 opened wire FULLY forced; ZMod 13: all 13 fold-consistent forged openings pass the FS-bound verifier, the binding cuts to the collision fiber {1,2,8} — [COMMIT-CR] made concrete); residual [RECURSE-full-resid] (root absorption into FS transcript, sumcheck-oracle opening, twoX/domain points, query multiplicity, Loom bridges) + floors inherited
import Compiler.SumcheckConformance  -- [PROVER-sumcheck] conformance vector: Loom's mle/roundSum instantiated at a fixed m=3 BabyBear table (LSB-first index convention pinned), all reference values KERNEL-DECIDED + the chain identities (roundSum_zero/_succ/_last) instantiated as theorems; writes prover/testdata/sumcheck_conformance.json for the UNVERIFIED Rust sumcheck engine to reproduce — vector agreement, never refinement
import Compiler.PredCompile  -- the general Pred → ConstraintSystem compiler, with sound/complete witness lowering and explicit residuals for order/oracle/quantified atoms
import Compiler.CanonicalPolicyAdmission  -- committed, versioned Pred records are resolved and checked only through the compiled predicate path; the legacy arbitrary portal remains an explicit cutover residual
import Compiler.DescriptorEval  -- EVM decompilation Stage 0, the ROUTABILITY half: fillAux evaluates a Lean-emitted ConstraintDescriptor over its own gates in emission order (the Lean side of the plan, not a Rust twin — d55ef32 deleted that); fillAux_gates_hold + fillAux_emit_holds + evmAddCandidate_holds/pins PROVED, so the five anvil-vector exhibits and the two refusals (forged claim, single-wire +1) are law-9 non-vacuity witnesses of theorems, thrown as #eval teeth; writes prover/testdata/evm_stage0_add_witness_v{1..5}.json (4,131 canonical words each) for the generated-glue reader (Lane B). Units recounted in Lean: 3,298 gates (1,665 add / 1,633 mul), 4,131 wires, 850 pins, 768 range bits + 17 carries.
import Compiler.EvmStage0NativeDeployment  -- EVM decompilation Stage 0, the NATIVE SEAM: work 9103 / carrier 206 / codecs 9007–9009 register the u256-add descriptor as an Instruction on the derived path — the 7-segment KernelCall (x,y,z public; xBits,yBits,zBits,carry witness; call_fullyWellFormed), instruction X Y Z with encodeBoundary as the 48-list public inputs, clause 407 + byte controller, the extended manifest/artifact/registry/DeploymentJoin and a new BuildTarget; NativeGlueGen now EMITS the descriptor rows (WORK_n_ROWS: 3,298 (op,aKind,a,bKind,b,out) tuples, WORK_n_ZEROS: 850; gateOfRow_rowOfGate left-invertible) into prover/generated/evm_stage0_add_aux.rs, and Rust only evaluates rows and returns 4,131 words — descriptorHoldsCheck judges on the Lean side (the predicate d55ef32 deleted stays deleted). Pinned: honest_certified (all in-range X,Y), forged_claim_refused (publicPrefixMismatch), unregistered_clause_refused, work_9103_pinned, work_9104_absent; eight throw-teeth exhibits; the five Lane-A witness vectors byte-identical through dispatch_native (prover/tests/evm_stage0_dispatch.rs).
import Compiler.CommittedTerminalRealizer  -- EVM decompilation Stage 0, the PROOF seam scouted and its first realizer: CommittedTerminal (GateMleExt6.lean:246) is a two-field record whose TYPE carries no authentication — ⟨mle …, rfl⟩ inhabits it vacuously, and the controller never names it (its receipt carries seven factored Ext6Q terminals on faith); said loudly. The realizer at FULL-WORD resolution (the only proved extractor needs 2^m ≤ t; a sampled realizer would assume [ERASURE-list]): a strict six-lane Ext6L carrier reusing ext6Mul_correct (the lazy Fin 6 → closure costs 6^m in nested products — paid once), mle_gammaResidualTable_sparse (the MLE is Σ_k γ^k res_k χ_{enc k}(r) over the residual list, linear not 2^m), the computable realize : … → Except Failure Ext6L, realize_sound consuming only S.commit_injective, committedTerminalOfBinding at the committed trace, honestRounds_closes_realized. Kernel-decided on the emitted 23-residual demoDescriptor under an ideal commitment AND an identity-suite Merkle: complete, forged value refused, forged word refused, tampered trace nonzero. Stage 0 (4,148 residuals, m = 13) runs as a compiled exhibit: honest accepted with terminal 0, forged refused at the honest root. Remaining to a real time-to-proof, sized: [CT-sampled] ~250 + the list-decoding seam, [CT-factored7] ~150, [CT-controller-lanes] ~400, [CT-merkle-profile] ~120 + CR game, [CT-compose] ~150; no Rust needed at full word.
import Compiler.CommittedTerminalFactored7  -- [CT-factored7] the receipt's seven factored Ext6Q terminals are no longer on faith: laneTerminal7 with read_laneTerminalKind (each = the terminal functional evaluated at the lifted word), TerminalOpenings inhabited from the opened word, realize7 + realize7_sound (lane equality at the committed trace under the named BindingCommitment), factored7_closes_realized. CORRECTED statement: "factored product = single realized terminal" is FALSE off the cube (GateMleExt6 §3), kernel-refuted on the demo (factored7_ne_single).
import Compiler.CommittedTerminalCompose  -- [CT-compose] the ONE ledger theorem for the full-word gate proof: gateProof_sound — accepted ⇒ descriptorHolds ∨ the gamma-zero event ∨ AdaptiveAcceptsFalse on the honest MLE — with Fintype Ext6Q built (card_ext6 : |Ext6Q| = p^6; none existed), readExt6_injective, the gamma event priced (gammaZero_prob_le ≤ (N−1)/|F|), the terminal at 0 under binding, and sumcheck_prob_le ≤ m·1/|F| (SHARP, d = 1; the m·2/|F| + 0 the brief asked is its corollary).
import Compiler.CommittedTerminalController  -- [CT-controller-lanes] the computable controller: check : … → Except Failure (Receipt Root m) with check_accepts by reflection, gateProof_sound_lane, an honest lane prover via residualSum_sparse (readPoly1_laneRound = mleHonest), receipt_complete / receipt_refuses_tamper / receipt_refuses_false_claim — the demo (m = 5) kernel-decided, and STAGE 0 (4,148 residuals, 13 rounds) as a compiled exhibit: the honest (1,2) proof ACCEPTED END TO END with terminal 0, a forged word refused at the root, at a round check, and at the terminal. The existing noncomputable controller is untouched; its obstruction is exhibited (AdjoinRoot.instField on every Receipt field, toExt6 in digestToExt6, the Finsupp aggregate). Remaining, sized: [CT-factored-prover] ~300, [CT-fiat-shamir-lanes] ~200 (the hash is a def), [CT-joint-price] ~60, [CT-sampled], [CT-merkle-profile].
import Compiler.CommittedTerminalFiatShamir  -- [CT-fiat-shamir-lanes] + [CT-joint-price]: the Stage-0 receipt made NON-INTERACTIVE under the tree's own keystone, not an invented oracle model. The controller's protocol is a Reduction (k = m+1: the γ round + m sumcheck rounds; verify IS check) with a PROVED RbrKnowledgeSoundness instance (round 0 priced by gammaZero_prob_le, rounds 1..m by one root, card_agreeFinset_lt); gateProof_fs_sound := fsKeystone_proved.sound at this instance, read out as (t + (m+1)) · (0 + (N−1)/|F| + m·(1/|F|)) in gateProof_fs_sound_reading. The deployed oracle is cSHAKE256 over a lawful-codec encoding of the transcript prefix (encodeMove_injective); fsCheck reflects into fiatShamir (fsCheck_ok_fiatShamir); the causal prover fsProve is complete. Demo kernel-decided (accepted; γ+1 refused as challengeMismatch though check accepts it — the fiatShamir_teeth shape); Stage 0 compiled: honest FS receipt accepted, altered challenge refused, a forged word's own FS run refused. THE PRICE, one expression, every term visible: stage0Receipt_price = (t + 14)·(0 + 4147/p⁶ + 13·(1/p⁶)) with S : BindingCommitment named (only S.commit consumed at full word), stage0Price_value = 4160/2013265921⁶ < 2^−173 by norm_num — FULL-WORD label: [CT-sampled] and [CT-merkle-profile] are not in it; "the deployed cSHAKE realizes the oracle" is [FS-ROM].
import Compiler.CommittedTerminalFactoredProver  -- [CT-factored-prover]: the honest prover for the seven factored openings — dense bit-corner tables + pairwise fold, check7 / check7_accepts, gateProof7_sound, sumcheck7_prob_le, and the bridge gammaBatched_eq_sum_table; Stage 0 compiled, demo decided (check7_complete_demo). Named, not closed: [CT-factored-prover-honest] (FactoredProverHonest : the fold messages read to factoredRounds), with its consumer factoredProver_complete_of_honest PROVED.
