"""
ITEM 3, ADDENDUM -- DOES THE sigma SCHEDULE ACTUALLY MIX THE CRT SLOTS,
ROUND BY ROUND?

WHY THIS EXISTS.  The prime-q lane closed eprint 2023/822 against us structurally
(Assumption 1, "there exists m with m | q", is unsatisfiable at prime q).  But it
named one concrete decisive check, because the CHEAP leg of that attack --
linearization -- is modulus-agnostic and survives:

  "pull the sigma exponents from the versioned spec and check whether they
   generate a TRANSITIVE subgroup of the 8 CRT slots.  If sigma is conjugation
   (X -> X^31), the cipher decomposes into 8 independent F_{q^2} ciphers."

That check is load-bearing for THIS lane's item-3 answer too: rha_groebner_cico.py
reading (B) assumes the sigma layer couples slots so the CICO system does NOT
decompose.  If it decomposes, the Grobner numbers move.

SETUP, from the spec /Users/ember/src/ring-ro-hash/sigma_poseidon.py frog_like():
  d = 16, so the relevant group is (Z/32)*, order 16.
  q mod 32 = 31, so <q> = {1, 31} and there are 16/2 = 8 CRT slots
  (matching R_q = (F_{q^2})^8).
  sigma_k acts on the SLOT INDEX by multiplication by k on (Z/32)*/{1,31}.
  Round schedule, verbatim from the spec:
      exps[r] = (2d-1) if r % 3 == 2 else pow(5, 1 << ((r // 3) % 4), 2d)
"""
D = 16
MOD = 2 * D           # 32
NR = 30               # RF=8 + RP=22


def units(m):
    from math import gcd
    return [x for x in range(1, m) if gcd(x, m) == 1]


U = units(MOD)
Q_MOD = 31            # q mod 32
FROB = {1, Q_MOD}     # <q>, the subgroup we quotient by to get slots

# slots = cosets of <q> in (Z/32)*
cosets, seen = [], set()
for u in U:
    if u in seen:
        continue
    c = frozenset({(u * f) % MOD for f in FROB})
    cosets.append(c)
    seen |= c
slot_of = {u: i for i, c in enumerate(cosets) for u in c}
NSLOT = len(cosets)

print("=" * 78)
print("SETUP")
print("=" * 78)
print(f"  (Z/{MOD})* has order {len(U)};  q mod {MOD} = {Q_MOD};  <q> = {sorted(FROB)}")
print(f"  number of CRT slots = {NSLOT}   (spec says R_q = (F_q^2)^8)")
assert NSLOT == 8, "slot count disagrees with the spec"


def slot_perm(k):
    """the permutation sigma_k induces on the 8 slot INDICES."""
    p = [0] * NSLOT
    for c_i, c in enumerate(cosets):
        u = min(c)
        p[c_i] = slot_of[(k * u) % MOD]
    return tuple(p)


IDENT = tuple(range(NSLOT))

exps = [(2 * D - 1) if r % 3 == 2 else pow(5, 1 << ((r // 3) % 4), 2 * D)
        for r in range(NR)]

print()
print("=" * 78)
print("PER-ROUND SLOT ACTION -- the measurement nobody had made")
print("=" * 78)
print(f"  {'round':>5} {'sigma exp':>10} {'slot permutation':>28} {'mixes slots?':>14}")
trivial_rounds = []
for r in range(NR):
    k = exps[r]
    p = slot_perm(k)
    triv = (p == IDENT)
    if triv:
        trivial_rounds.append(r)
    if r < 15 or triv:
        print(f"  {r:>5} {k:>10} {str(p):>28} {'NO -- IDENTITY' if triv else 'yes':>14}")
print(f"  ... (schedule is periodic with period 12)")

print()
print("=" * 78)
print("⚑ FINDING")
print("=" * 78)
print(f"  rounds whose sigma layer acts TRIVIALLY on the slot index: {trivial_rounds}")
print(f"  that is {len(trivial_rounds)}/{NR} rounds = {100*len(trivial_rounds)/NR:.0f}% of the schedule")

# maximal run of consecutive slot-trivial rounds
best, cur = 0, 0
for r in range(NR):
    cur = cur + 1 if slot_perm(exps[r]) == IDENT else 0
    best = max(best, cur)
print(f"  longest run of CONSECUTIVE slot-trivial rounds: {best}")

# the group generated by all exponents used
gen = {1}
changed = True
while changed:
    changed = False
    for k in set(exps):
        for x in list(gen):
            y = (x * k) % MOD
            if y not in gen:
                gen.add(y)
                changed = True
orbit = {slot_of[(g * min(cosets[0])) % MOD] for g in gen}
print(f"  group generated by ALL exponents used: order {len(gen)}")
print(f"  its orbit on slot 0: {sorted(orbit)}  -> "
      f"{'TRANSITIVE (C3 satisfied)' if len(orbit) == NSLOT else 'NOT TRANSITIVE -- DECOMPOSES'}")
assert len(orbit) == NSLOT

print("""
  READING, and both halves matter:

  ⚑ GOOD: taken as a whole the schedule IS transitive on the 8 slots, so C3 is
    satisfied and the worst case the prime-q lane named -- a cipher that splits
    into 8 independent F_{q^2} ciphers -- does NOT occur.  rha_groebner_cico.py
    reading (B) stands, and with it the item-3 verdict.

  ⚠ BUT: the sigma exponent is 31 = 2d-1 on every third round, and 31 is exactly
    q mod 32, so sigma_31 lies in <q> and acts as the IDENTITY on the slot INDEX.
    It applies a Frobenius WITHIN each slot and moves nothing between slots.
    Worse, the r//3 schedule cycles 5 -> 25 -> 17 -> 1, and 5^8 = 1 mod 32, so
    one block in four uses the IDENTITY automorphism, whose layer
    x + c*sigma_1(x) = (1+c)*x is a pure R_q-scalar -- slot-diagonal, zero
    mixing.""")
print(f"""
  ⚑ CONSEQUENCE: there is a run of {best} CONSECUTIVE rounds carrying NO slot-index
    mixing at all.  Over such a window the permutation IS slot-diagonal, i.e. it
    decomposes into 8 independent maps over F_{{q^2}}.  That is precisely the
    round-skipping resource an algebraic attacker wants, and it is free.

    It does not break anything measured here -- the surrounding rounds restore
    transitivity, and item 3 clears by hundreds of bits.  But it is a schedule
    defect with zero cost to fix: choose exponents so that no round is
    slot-trivial (drop the 5^8 = 1 block, and pair every sigma_31 round with a
    slot-moving one).  A round that costs constraints and mixes nothing is the
    cheapest thing in this design to correct.""")
